bin/build_rpm.sh, resources/centos6/after_install.sh, resources/centos7/after_install.sh
While the brewtils changes makes it less possible to build the
system from what we have currently, its more appropriate for
development cases.
The resources changes are required due to the new specifications.
=> Adding fixes for RPM building.

bin/rpm_build.sh
=> Tweaking rpm script to ignore magic comment line

docker/docker-compose/docker-compose.yml
Small change to the compose file to make it more obvious what needs to change in order to support remote plugins.
=> Changing compose publish host location for better visibility

README.md
Updates the README for version 3.
I don't really want to duplicate too much information that's already in the beer-garden.io docs. I think the README should steer people to those as much as possible (but I may have cut too much out :fearful:)
=> Readme changes for version 3

src/app/beer_garden/api/http/client.py, src/app/beer_garden/api/http/handlers/v1/admin.py, src/app/beer_garden/api/http/handlers/v1/instance.py, src/app/beer_garden/api/http/handlers/v1/job.py, src/app/beer_garden/api/http/handlers/v1/logging.py, src/app/beer_garden/api/http/handlers/v1/request.py, src/app/beer_garden/api/http/handlers/v1/role.py, src/app/beer_garden/api/http/handlers/v1/system.py, src/app/beer_garden/api/http/handlers/v1/token.py, src/app/beer_garden/api/http/handlers/v1/user.py
This PR updates Beergarden to reflect the changes from beer-garden/brewtils#150
=> Brewtils parser

README.md, src/app/beer_garden/db/mongo/parser.py, src/app/example_configs/config.yaml
=> Example config fix

src/app/beer_garden/__init__.py, src/app/beer_garden/instances.py, src/app/beer_garden/queue/rabbit.py, src/app/test/queue/rabbit_test.py
This PR moves some things out if the `instance` module into the `queue` package.
=> Mq refactor

src/app/beer_garden/api/__init__.py, src/app/beer_garden/api/http/handlers/v1/instance.py, src/app/beer_garden/events/events_manager.py, src/app/beer_garden/plugin.py
This PR adds support for updating an instance's metadata.
=> Adding instance metadata update api

src/app/beer_garden/db/mongo/models.py, src/app/beer_garden/queue/rabbit.py, src/app/test/db/mongo/models_test.py
This PR is the other half of beer-garden/brewtils#185. 
- Adds namespace fields to various database models
- Makes the namespace a component of the rabbit queues / routing keys.
=> Namespaces

src/ui/package-lock.json, src/ui/package.json, src/ui/src/js/controllers/command_view.js
This PR bumps the required version of the `@beer-garden/builder` package.
=> Namespace ui

src/ui/src/js/controllers/request_index.js
This fixes #409 - it adds a system version column to the request index page.
=> Adding system version column to request index page

src/app/beer_garden/api/http/__init__.py, src/app/beer_garden/api/http/handlers/v1/garden.py, src/app/beer_garden/db/mongo/models.py, src/app/beer_garden/garden.py, src/app/beer_garden/router.py
This PR splits the Gardens REST API into the standard two-handler structure.
=> Breaking out Gardens API endpoints

src/app/beer_garden/api/http/__init__.py, src/app/beer_garden/api/http/handlers/misc.py, src/app/beer_garden/api/http/handlers/v1/namespace.py, src/app/beer_garden/db/api.py, src/app/beer_garden/db/mongo/api.py, src/app/beer_garden/namespace.py, src/ui/src/js/configs/routes.js, src/ui/src/js/controllers/admin_system.js, src/ui/src/js/services/command_service.js, src/ui/src/js/services/system_service.js, src/ui/src/js/services/utility_service.js
This PR addresses some of my comments on #434.
It also helps with namespace support on the frontend.
=> Namespace tweaks

src/ui/src/js/controllers/request_index.js
This PR uses the frontend namespace on the request index page.
=> Using namespace in request index page query

src/app/beer_garden/api/http/__init__.py, src/app/beer_garden/api/http/handlers/v1/request.py, src/app/beer_garden/app.py, src/app/beer_garden/events/handlers.py, src/app/beer_garden/events/processors.py, src/app/beer_garden/router.py
This correctly forwards requests to the garden they need to get to.
=> Ns routing

src/app/beer_garden/router.py
This PR enables forwarding instance start and stop requests.
=> Instance status changes now fowarded to correct garden

src/app/beer_garden/api/entry_point.py, src/app/beer_garden/app.py, src/app/beer_garden/events/handlers.py, src/app/beer_garden/router.py, src/app/beer_garden/systems.py, src/app/example_configs/config.yaml
I was testing out v3 and discovered that we don't cache the current gardens at startup. So I updated that and also updated how we handle garden update events to cache the results.
Discovered that we were mapping the wrong field from the config for default namespace for plugins. Fixed that mapping
=> Debugging Finds

src/ui/src/js/run.js, src/ui/src/js/services/event_service.js
This PR makes the frontend check the status of the websocket connection every five seconds. It will attempt to reconnect if not currently connected.
=> Websocket reconnect

src/app/beer_garden/db/mongo/models.py
This PR reorders the index fields for the System model. It also changes some error strings.
=> Db updates

src/app/beer_garden/events/handlers.py, src/app/beer_garden/local_plugins/manager.py, src/app/beer_garden/queue/rabbit.py, src/app/beer_garden/router.py, src/app/beer_garden/systems.py
This PR helps with the system removal and rescanning functionality.
=> System updates

src/app/beer_garden/api/http/handlers/misc.py
This PR makes minor tweaks to the handlers in `misc.py`.
=> Misc refactors

src/app/beer_garden/api/http/handlers/v1/garden.py, src/app/beer_garden/app.py, src/app/beer_garden/events/handlers.py, src/app/beer_garden/events/processors.py, src/app/beer_garden/garden.py, src/app/beer_garden/router.py
Opening the PR so I can see my changes easier
=> Routing debugging

src/app/beer_garden/events/handlers.py, src/app/beer_garden/router.py
This removes the parent when forwarding and adds it back afterwards.
=> Fixed Remote Parent Issue

src/ui/src/partials/command_index.html
Fixed Make it Happen button on command index page.
=> Fixed broken link for Make it Happen button

src/ui/src/js/controllers/request_index.js, src/ui/src/partials/command_index.html, src/ui/src/partials/request_view.html
Added hyperlink in request view to system view.
Fixes #379
=> Request system link

src/app/beer_garden/router.py
Added the Delete System to forwarding options
=> Added Delete System to routable

src/ui/src/index.html
This is a minor PR that removes an unnecessary `div` and stops the browser from requesting `favicon.ico` before we can tell it the actual favicon file name.
=> Frontend cleanup

src/ui/src/js/controllers/admin_system.js, src/ui/src/partials/admin_system.html
This fixes the link issue on the systems admin page, and also fixes an issue where going to the page would overwrite the global systems list.
=> Fixing link issue with systems admin page

src/ui/src/js/run.js
Removed Websocket logger to Console.
=> Removing Web Socket Loggging to Console

src/app/beer_garden/db/mongo/api.py
This PR adds debug logging for the case where the connection to the database is failing and you'd like to know why.
=> Adding debug logging for mongo connect

src/ui/src/js/configs/routes.js, src/ui/src/js/controllers/request_view.js, src/ui/src/partials/request_view.html
This PR reworks the request view page to use the event service rather than periodic polling.
=> Reworking request view page to use event service

src/ui/src/js/controllers/admin_system.js, src/ui/src/js/controllers/command_view.js, src/ui/src/js/run.js, src/ui/src/js/services/event_service.js, src/ui/src/partials/admin_system.html
This PR reworks the admin systems page to use the master systems list.
=> Admin systems page now uses global systems list

src/ui/src/index.html, src/ui/src/styles/custom.css
This PR changes the `position` of the top nav bar to `fixed`.
=> Changing nav bar to fixed position

src/ui/src/index.js, src/ui/src/js/controllers/request_view.js, src/ui/src/partials/request_view.html
Add button to download output as a json, txt, or html file.
Fixes #361
=> Added button to download output

src/ui/src/js/controllers/request_view.js, src/ui/src/partials/request_view.html
Added buttons to make output or parameter larger.
Fixs #170
=> Added button to expand output and parameter.

src/app/beer_garden/db/mongo/models.py, src/ui/src/js/configs/dt_renderer.js, src/ui/src/js/controllers/command_index.js, src/ui/src/js/controllers/system_view.js, src/ui/src/partials/command_index.html, src/ui/src/partials/system_view.html
Added show hidden button to system view and command index, and updated models to include hidden in command decorator. PR is dependent on PR beer-garden/brewtils#206 for adding hidden to models in brewtils.
Fixes #269
=> Hide button

src/ui/src/index.html, src/ui/src/js/controllers/command_index.js, src/ui/src/js/controllers/request_index.js, src/ui/src/js/controllers/system_index.js, src/ui/src/partials/about.html, src/ui/src/partials/admin_role.html, src/ui/src/partials/admin_system.html, src/ui/src/partials/admin_user.html, src/ui/src/partials/command_index.html, src/ui/src/partials/command_view.html, src/ui/src/partials/job_index.html, src/ui/src/partials/request_view.html, src/ui/src/partials/system_index.html
This is the first round of 508 Compliance testing. Utilized the ANDI package sweet to inspect each page, then used Google's LightHouse application to get a score.
Pages Checked:
Fixes #23
=> 508 Compliance

src/app/beer_garden/api/entry_point.py, src/app/beer_garden/app.py, src/app/beer_garden/config.py, src/app/beer_garden/queue/rabbit.py, src/app/example_configs/config.yaml, src/app/test/config_test.py
Migrating over the usage of AMQ to MQ. 
In response to #377
=> Migrated the usage of AMQ to MQ.

src/app/beer_garden/systems.py
This PR fixes issues associated with multi-instance plugins.
=> Multi plugins

docker/docker-compose/docker-compose.yml, src/app/beer_garden/app.py, src/app/beer_garden/config.py, src/app/example_configs/config.yaml
Added env options to allow for docker-compose deployment of children. That way it is easier to stand up example instances for users.
=> Added env options for Parent connections

src/app/beer_garden/config.py, src/app/test/router_test.py
=> Exceptions should actually be raised

src/app/beer_garden/api/http/__init__.py, src/app/beer_garden/api/http/handlers/v1/admin.py, src/app/beer_garden/api/http/handlers/v1/logging.py, src/app/beer_garden/config.py, src/app/beer_garden/log.py, src/app/beer_garden/router.py, src/app/example_configs/config.yaml, src/app/example_configs/plugin-logging.yaml, src/app/test/log_test.py
This PR reworks how plugin logging configuration works. Depends on / enables beer-garden/brewtils#221.
=> Flex logging

src/app/beer_garden/api/http/handlers/v1/instance.py, src/app/beer_garden/plugin.py, src/app/beer_garden/requests.py
Fixes an issue where errors were not propagating correctly.
=> Log retrieval now handles ERROR requests

src/ui/src/js/controllers/request_view.js
=> Fallback to current garden name for v2 requests Pour it Again

src/ui/src/index.html
Moved the admin options back up in the menu. Not sure how I like it, but if it has been bugging us then it will annoy people in it everyday.
Fixes #534
=> Admin menu

src/ui/src/index.html
Updated the top search bar to search commands as well as systems.
Fixes #543
=> Added ability to search commands along with Systems

src/app/beer_garden/router.py
Fixes an error handling case in the routing module
=> Routing event handler shouldn't take action for error events

src/app/beer_garden/db/api.py, src/app/beer_garden/systems.py
Fixes a bug with non-dev version systems incorrectly failing validation.
=> Fixing issue with systems incorrectly failing validation

src/ui/src/index.html, src/ui/src/styles/custom.css
Addressing two of the three topics brought up in #565
=> Added scroll bar to drop down and Empty Results Search text

src/app/beer_garden/api/entry_point.py, src/app/beer_garden/app.py, src/app/beer_garden/config.py, src/app/example_configs/config.yaml
Updates the config to use Enabled instead of Enable.
Fixes #531
=> Config Enable to Enabled

src/app/beer_garden/local_plugins/manager.py, src/app/test/local_plugins/manager_test.py
=> Correctly setting MAX_INSTANCES in beer.conf

src/app/beer_garden/log.py
Handing PR changes provided in #571
=> Rolling back the file check

src/app/beer_garden/garden.py, src/app/beer_garden/local_plugins/env_help.py, src/app/beer_garden/monitor.py, src/app/beer_garden/requests.py, src/app/beer_garden/router.py
Some new linting issues are appearing in Travis. Some of these files were not in recent PRs, so we need to address them separately. 
To recreate the same black errors I had to reinstall black
`pip install --ignore-installed black`
=> Black Formatter Upgrade Issues

src/app/beer_garden/api/http/__init__.py, src/app/beer_garden/api/http/base_handler.py, src/app/beer_garden/api/http/handlers/v1/command.py, src/app/beer_garden/commands.py, src/app/beer_garden/db/api.py, src/app/beer_garden/db/mongo/api.py, src/app/beer_garden/db/mongo/models.py, src/app/beer_garden/db/mongo/util.py, src/app/beer_garden/errors.py, src/app/beer_garden/systems.py, src/app/test/db/mongo/models_test.py, src/ui/src/js/configs/routes.js, src/ui/src/js/services/command_service.js, src/ui/src/partials/command_index.html, src/ui/src/partials/system_view.html
This PR removes `Command` as a top-level database model. It's now an EmbeddedDocument owned by the `System` model.
Depends on https://github.com/beer-garden/brewtils/pull/232
=> Child commands

src/ui/src/js/run.js
=> Adding jquery and lodash objects to window

src/app/beer_garden/db/api.py, src/app/beer_garden/db/mongo/api.py, src/app/beer_garden/db/mongo/models.py, src/app/beer_garden/systems.py, src/app/requirements.in, src/app/requirements.txt, src/app/setup.py
This fixes the issue with multiple instance local plugins failing to start
=> Multi instance

src/app/beer_garden/db/mongo/api.py, src/app/beer_garden/instances.py, src/app/beer_garden/plugin.py, src/app/beer_garden/queue/rabbit.py, src/app/beer_garden/requests.py, src/app/beer_garden/router.py, src/app/beer_garden/systems.py
This PR lets the router add kwargs to the operation. It uses this to add any database models it looks up in the course of determining where to route the operation.
This then modifies the business logic to use those kwargs if available.
=> Db efficiency

src/app/beer_garden/router.py
Added some verbiage to make it more clear for a user who accidentally mistypes a manual request.
Fixes #563
=> Updated Unknown Garden Exception

src/app/beer_garden/db/mongo/parser.py
This is part of beer-garden/beer-garden#611. It depends on and enables https://github.com/beer-garden/brewtils/pull/239.
=> Making MongoParser work with updated SchemaParser

src/app/beer_garden/requests.py
=> Missing request now raises correct error

src/app/beer_garden/api/entry_point.py, src/app/beer_garden/api/http/__init__.py, src/app/beer_garden/api/http/authorization.py, src/app/beer_garden/app.py, src/app/beer_garden/local_plugins/runner.py
This PR has a couple of things that fell out of investigating #611.
- Adds type hints in some places
- Names some threads to help with debugging
- ~Adds a __main__ module to the HTTP entry point package. This allows running only the http entry point without any of the overhead of the main process.~ jk, that needs more work
=> Misc updates

src/app/beer_garden/local_plugins/manager.py
Updates the shutdown process to concurrently run 10 plugin shutdowns until they are all closed. 
Fixes #567
=> Uses ThreadPool to shutdown plugins

src/app/beer_garden/api/http/__init__.py, src/app/beer_garden/api/http/base_handler.py, src/app/beer_garden/api/http/handlers/v1/instance.py, src/app/beer_garden/api/http/handlers/v1/request.py, src/app/beer_garden/plugin.py, src/app/beer_garden/requests.py, src/app/beer_garden/router.py, src/app/beer_garden/scheduler.py, src/app/test/scheduler_test.py
=> Moving request waiting up into entry point

src/app/beer_garden/api/http/handlers/v1/instance.py, src/app/beer_garden/plugin.py, src/app/beer_garden/router.py
This PR is part of #611.
It splits out the instance heartbeat method so an event isn't published every time.
=> Heartbeats

src/app/beer_garden/plugin.py, src/app/beer_garden/requests.py, src/app/test/config_test.py, src/app/test/conftest.py, src/app/test/requests_test.py
Added namespace to ```choices_request``` to resolve ```brewtils.errors.ModelValidationError```
You can test using command ```say_specific_with_choices_argument``` from the dynamic plugin found in https://github.com/beer-garden/example-plugins
Fixes #630 #637
=> Fixed validation error for choices

src/app/beer_garden/requests.py, src/app/beer_garden/router.py, src/app/test/requests_test.py
=> Using executor for executing CREATE_REQUESTS in async context

src/app/beer_garden/systems.py
This starts #641, but doesn't close it.
=> Checking for duplicate instance names before update

src/app/beer_garden/db/mongo/pruner.py, src/app/test/db/mongo/pruner_test.py
Fixes #604 in version 3.
Originally developed in beer-garden/bartender#109
=> Pruner ResultSet no longer caches

src/ui/src/partials/request_view.html
Changed icons for resizing output or parameter to be arrows in the request view page.
Fixes #649
=> Changed icons to be arrows issue #649

src/app/beer_garden/router.py
=> Request create namespace defaults to local garden name

src/ui/src/index.js, src/ui/src/js/configs/routes.js, src/ui/src/js/run.js, src/ui/src/partials/landing.html
This fixes #662. It changes the default landing page to the Systems page.
=> Removing landing page

src/app/beer_garden/api/http/handlers/v1/admin.py
Fixed the rescan issue for permissions.
=> Fix Rescan Permissions

src/app/beer_garden/requests.py
This is required for any requests that are internally generated (i.e. Dynamic Command Validation). Now all requests will get sent through the Router class to ensure that the proper Garden is handling the request.
=> Route all requests that are internally generated to the Router.

src/app/beer_garden/api/http/handlers/v1/logging.py, src/app/beer_garden/app.py, src/app/beer_garden/config.py, src/app/beer_garden/log.py, src/app/beer_garden/monitor.py, src/app/example_configs/config.yaml
Fixes #636, depends on beer-garden/brewtils#255
=> Separate logging config for local plugins

src/app/beer_garden/config.py, src/app/beer_garden/local_plugins/manager.py, src/app/example_configs/config.yaml
This fixes #686 for v3, but I'm not super happy about the config name. Thoughts?
=> Allowing specific host environment variable expansions

src/app/beer_garden/app.py, src/app/beer_garden/monitor.py
Fixes a bug with shutdown procedure when a local plugins logging config override isn't specified.
=> Fixing shutdown bug with plugin log config file monitors

docker/docker-compose/docker-compose.yml, src/app/beer_garden/api/stomp/__init__.py, src/app/beer_garden/api/stomp/server.py, src/app/beer_garden/api/stomp/stomp_manager.py, src/app/beer_garden/config.py, src/app/example_configs/app-logging.yaml, src/app/example_configs/config.yaml
I improved encapsulation for stomp's connection class and made some minor changes to the entry config for stomp to make more clear what is for ssl.
Fixes #695
=> Issue/695 Improved Encapsulation for Stomp's Connection Class

.travis.yml, src/ui/package-lock.json, src/ui/package.json
=> Npm deploy

src/app/beer_garden/app.py, src/app/beer_garden/commands.py, src/app/beer_garden/config.py, src/app/beer_garden/garden.py, src/app/beer_garden/log.py, src/app/beer_garden/metrics.py, src/app/beer_garden/monitor.py, src/app/beer_garden/namespace.py, src/app/beer_garden/plugin.py, src/app/beer_garden/queues.py, src/app/beer_garden/requests.py, src/app/beer_garden/router.py, src/app/beer_garden/scheduler.py, src/app/beer_garden/systems.py
Went through all of the top level services and added doc strings to the files and functions where I saw it was missing.
=> Updated Doc Strings

src/app/beer_garden/config.py, src/app/test/config_test.py
Logs the actual error if config migration fails.
=> Logging actual error if config migration fails

src/app/beer_garden/api/http/__init__.py, src/app/beer_garden/api/stomp/__init__.py, src/app/beer_garden/db/mongo/pruner.py, src/app/beer_garden/local_plugins/manager.py, src/app/beer_garden/local_plugins/runner.py, src/app/beer_garden/plugin.py, src/app/beer_garden/requests.py, src/app/example_configs/app-logging.yaml
Updates the levels for some logging statements.
=> Updating application log levels

src/app/beer_garden/router.py
=> Fixing routing execution issue

rpm/centos7/scripts/after_install.sh
Slightly tweaks the directory structure for plugin logs.
=> Changing default plugin log directory structure

src/app/beer_garden/app.py
=> Multiprocessing manager process ignores SIGTERM

src/app/beer_garden/app.py
=> More aggressive signal ignore

src/app/Makefile, src/ui/Makefile
Adds some additional docker tags
=> Docker tags

docker/docker-compose/docker-compose.yml
Minor cleanup and version pinning in compose file.
=> Using "3" tag for beergarden services, pinning external image tags

src/ui/src/js/controllers/request_view.js
=> Better filtering in request view page event handler

src/ui/src/js/controllers/request_view.js, src/ui/src/partials/request_view.html
Disables `Pour it Again` button if system or command is not found.
Fixes #624
=> Disables Pour it Again issue #624

src/ui/src/partials/admin_system.html
Changed word to correct word described in issue #768 
Fixes #768
=> issue #768

.github/workflows/pr-actions.yml
Adding Github Actions for PRs only
- PyTest
- Linting
- Coverage
=> PR Github Actions

.github/workflows/tag-actions.yml
Adding the Tag Actions for Releases
We still need DOCKER variables set.
https://github.com/actions/upload-release-asset
=> Tag actions

src/ui/src/js/controllers/admin_garden.js, src/ui/src/partials/admin_garden_index.html
Enables creating a garden through ui.
Found new issue #727 while testing.
Fixes #726
=> Enables creating a garden through ui issue #726

src/app/beer_garden/config.py
Fixes lint errors from merging PR #757.
=> fixed linting errors

src/app/beer_garden/systems.py
Improves failure handling during system removal.
Fixes #771.
=> Much more robust error handling during system purge

src/app/beer_garden/api/http/__init__.py, src/app/beer_garden/api/stomp/__init__.py, src/app/beer_garden/api/stomp/stomp_manager.py, src/app/beer_garden/app.py
This should fix the plugins from starting before the HTTP Entry point
=> Entry point events

src/app/beer_garden/api/stomp/stomp_manager.py
Move metadata into event object to fix error on shutdown
=> Moved metadata into event object

src/app/beer_garden/systems.py
Fixes #806, depends on beer-garden/brewtils#277
=> Updating system commands with empty list now works correctly

.github/workflows/pr-actions.yml, src/app/Makefile, src/app/beer_garden/files.py
This action compares the complexity results of the `base` reference to the `current` reference.  If any alterations/additions exceed the suggested [Cyclomatic Complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) of 10, an error is thrown.
Cyclomatic Complexity is not an end-all metric, but can be considered a code smell.  If something is flagged, double check the code and consider refactoring.
This action compares the security results of the `base` reference to the `current` reference.  The action uses a security-flavored linter (`bandit`) to analyze the code.
=> Adding Checkers for Code Complexity and Security to PR Actions

rpm/centos7/resources/service/beer-garden.service
Fixes #816 - changes the user that runs the beer-garden process.
=> Specifying user and group in systemd service file

src/app/beer_garden/systems.py
=> Always removing local runners when purging system

src/ui/src/partials/request_view.html
This fixes the most visible part of #813, but we should go through and verify this isn't an issue elsewhere.
=> Self-closing non-void tags are not great in HTML5

src/app/beer_garden/queues.py
=> Call System function for instance to get the Queue

src/app/beer_garden/log.py
This doesn't really close out #803, but I'm guessing at this point that's going to be closed as not reproducible. And I think this is useful to have.
=> Adding log message when logging config file is changed

.github/workflows/tag-actions.yml
Fixing the github Tag issue we fixed everywhere else
=> Fixing Github Tag

src/app/beer_garden/db/mongo/util.py
This is the database script to migrate Owner objects to Requests and Jobs. 
Requires #834 to be merged in first.
=> Adding the Owner Migration script

src/app/beer_garden/api/http/handlers/v1/request.py, src/app/beer_garden/db/mongo/models.py, src/app/beer_garden/requests.py, src/ui/src/js/configs/dt_renderer.js, src/ui/src/js/controllers/request_index.js
Added a hidden flag into the request model that gets set if the corresponding command is hidden when the request is created.
Dependent on PR beer-garden/brewtils#288
Fixes #414
=> Hiding requests if command is hidden

src/ui/src/js/controllers/request_index.js
=> Changing placement of parent request popover

src/ui/src/js/configs/dt_renderer.js
=> Changing checkbox captions on request index page

src/app/beer_garden/db/mongo/util.py
Fixes #868. Db migration script no longer depends on `has_parent` field existing.
=> Db migration works with very old requests, better error handling

.github/workflows/pr-actions.yml, .github/workflows/scripts/parse_diff_complexity.py
Trying to alter how the complexity checker action works so that only negative changes cause it to fail, not just changes in general.
=> Improving the complexity action output 

.github/workflows/pr-actions.yml
This is a test to see how the new tag for brewtils is going to work out.
Tester Tag:
=> Adding custom brewtils tag

src/app/beer_garden/namespace.py
Fixes #890, removes bad values.
=> Filtering out bad namespace values

.github/workflows/pr-actions.yml
Checks the environment variable to determine if we need to use the cache or pull in the changes from Brewtils.
=> Skip Cache if using specified brewtils branch

src/app/beer_garden/router.py
=> Actually fixing ssl forwarding

src/ui/src/js/controllers/admin_garden_view.js
Added additional steps to show any error messages that are returned from the API and error for Form Validation. 
Fixes: #903
=> Updated the UI for Garden Admin to handle Errors

src/ui/src/index.js
Resolves error from merging PR #910.
=> Resolves error from merge

src/app/beer_garden/router.py
Uses EasyClient for HTTP forwarding. Depends on beer-garden/brewtils#301.
=> Using EasyClient for HTTP forwarding

src/app/beer_garden/api/stomp/server.py, src/app/beer_garden/api/stomp/stomp_manager.py
Moved stomp reconnect loop up to manager so stomp entry point can still process events.
Dependent on PR #910 
Fixes #914
=> Stomp Reconnect Loop Break for Garden Change

src/app/beer_garden/db/mongo/api.py
Fixes #959 - an issue with the database layer incompletely converting to brewtils models.
=> Database layer serializes to string when converting to brewtils

src/app/beer_garden/config.py
=> More stomp spec changes

src/app/beer_garden/api/stomp/manager.py, src/app/beer_garden/router.py
This should help with #978. It only addresses one specific case though, so it doesn't fix the issue.
=> Deep copying connection parameters before modifying them

src/ui/src/js/controllers/request_view.js
Fixed #984. Child request view now starts collapsed.
=> Child request view starts as collapsed on request view page

src/app/beer_garden/api/http/handlers/v1/job.py, src/app/beer_garden/router.py, src/app/beer_garden/scheduler.py, src/ui/src/js/configs/routes.js, src/ui/src/js/controllers/job/create_request.js, src/ui/src/js/controllers/job/create_trigger.js, src/ui/src/js/controllers/job_view.js, src/ui/src/js/services/job_service.js, src/ui/src/partials/job_view.html
When updating a Job, takes the user back to the Edit Request page, then the Edit Trigger page.
Couldn't figure out how to update the text on the buttons, but the functionality is there.
Needs brewtils: issue/294
Depends on: https://github.com/beer-garden/brewtils/pull/308
=> Update Existing Jobs

src/app/beer_garden/requests.py
Fixes #982 - better error handling for request events coming in out of order.
=> Not logging errors for out of order request events from child gardens

src/app/beer_garden/db/mongo/models.py
Fixes #358.
Depends on beer-garden/brewtils#314.
=> Adding metadata field to command model

src/ui/src/partials/command_view.html
=> Fixing broken link targets

.github/workflows/integration_tests.yml
=> Integration tests should now use develop version of brewtils

src/app/beer_garden/api/http/handlers/v1/request.py
This fixes #1017 - gives a better error message when a request can't be created.
=> Better error message for request creation failure

src/ui/src/js/controllers/request_view.js
Fixes #1026 - only considers output size when deciding whether to display output.
=> UI only considers actual output when checking output size

src/app/beer_garden/db/mongo/models.py, src/app/beer_garden/scheduler.py, src/app/test/scheduler_test.py, src/ui/src/js/services/job_service.js
Fixes #1046. Adds a timeout field to the job model. Depends on beer-garden/brewtils#329.
=> Adding timeout field to scheduled jobs

src/app/beer_garden/requests.py
This fixes #932, handles the REQUEST_CANCELED event.
=> Handling REQUEST_CANCELED event

src/app/Dockerfile
Fixes #916 - sets the timezone in the docker image.
=> Setting timezone to UTC in docker image

src/app/beer_garden/router.py, src/app/test/router_test.py
Reverts beer-garden/beer-garden#1077
=> Revert "Overriding operation target garden if necessary"

src/app/requirements.txt, src/ui/package-lock.json
Post-release dependency version bumps.
=> Dependency version bumps

src/app/beer_garden/api/stomp/manager.py
This fixes #1102. It adds a lock around the stomp entry point's interaction with its end of the Pipe it uses to talk to the main process.
🙏🏼
=> Adding lock protection to stomp entry point pipe operations

src/app/beer_garden/api/authorization.py, src/app/beer_garden/api/http/__init__.py, src/app/beer_garden/api/http/authorization.py, src/app/beer_garden/api/http/base_handler.py, src/app/beer_garden/api/http/handlers/v1/role.py, src/app/beer_garden/api/http/handlers/v1/user.py, src/app/beer_garden/db/mongo/api.py, src/app/beer_garden/db/mongo/models.py, src/app/beer_garden/db/mongo/parser.py, src/app/beer_garden/db/mongo/util.py, src/app/beer_garden/db/mongo/validators.py, src/app/beer_garden/user.py, src/app/setup.cfg, src/app/test/api/http/unit/handlers/v1/roles_test.py, src/app/test/api/http/unit/handlers/v1/users_test.py, src/app/test/db/mongo/models_test.py, src/app/test/db/mongo/util_test.py, src/app/test/user_test.py
Closes #1089
Requires [brewtils/347](https://github.com/beer-garden/brewtils/pull/347) (tests will failed until brewtils PR is merged) (UPDATE: PR has been merged and tests should now be passing)
There's simultaneously a lot and kind of not really very much going on in this PR.  Looking at the diff isn't really going to be the best way to get a feel for what was done here.  Instead I suggest:
* Take a look a the [first commit](https://github.com/beer-garden/beer-garden/pull/1106/commits/9dd9c9af324f9654aa8ce5053876abfea01f15e3), where I renamed the existing `Role` model to `LegacyRole`.  I did this so that I didn't have to come up with some alternative name for the new `Role` model.
* Then look at the [second commit](https://github.com/beer-garden/beer-garden/pull/1106/commits/d2956c77f6f4 …
=> #1089 - New auth models and basic user http api

src/ui/package-lock.json
No updates for requirements.txt available.
=> bump dependency versions

src/app/beer_garden/requests.py
Closes #1271 
This PR aims to get rid of the error events for request state transitions entirely.  It also attempts to be at least nominally smarter about when to call `update_request` during the event processing, so that we're less likely to be publishing "REQUEST_UPDATED" events when in fact nothing has changed.  In the case of the websocket event spamming, this cuts the number of events down to about 1/3 of what they were in the case of a "grandchild" garden (From nearly 60 to around 20).
Event publishing and processing is still fundamentally flawed, but this PR should at least remove the error events and reduce the general event spamming.
Setup a remote garden that's two hops away (a "grandchild").  Task it from the local garden and make sure tasking works as expected.  In the local …
=> #1271 - Slightly reduce request event spam and silence transition error events

src/ui/src/index.html, src/ui/src/index.js, src/ui/src/js/configs/routes.js, src/ui/src/js/controllers/add_command_publishing_blocklist.js, src/ui/src/js/controllers/command_publishing_blocklist.js, src/ui/src/js/services/command_publishing_blocklist_service.js, src/ui/src/partials/command_publishing_blocklist.html, src/ui/src/templates/add_command_publishing_blocklist.html
Closes #1229 
Adds a UI for managing the command publishing blocklist.
The UI for interacting with the command publishing blocklist can be found at `<your_host_path>/commandblocklist` or using the link found in the admin drop-down button
=> issue #1229 Adds UI for Command Publishing Blocklist

src/app/beer_garden/app.py, src/app/beer_garden/command_publishing_blocklist.py, src/app/beer_garden/events/handlers.py, src/app/beer_garden/garden.py, src/app/test/command_publishing_blocklist_test.py
Closes #1283 
Syncs the CommandPublishingBlocklist between the child and the parent gardens on garden sync.
Depends on beer-garden/brewtils#399
=> issue# 1283 syncs the CommandPublishingBlocklist

src/app/beer_garden/requests.py
Closes #1330 
Made the changes suggested to remove the direct pika import from this file
=> Issue 1330: Change pika call

src/app/beer_garden/api/http/base_handler.py, src/app/beer_garden/authorization.py, src/app/beer_garden/db/mongo/api.py, src/app/beer_garden/db/mongo/models.py, src/app/beer_garden/db/mongo/util.py, src/app/beer_garden/errors.py, src/app/beer_garden/files.py, src/app/beer_garden/plugin.py, src/app/beer_garden/requests.py, src/app/test/db/mongo/api_test.py, src/app/test/db/mongo/util_test.py, src/app/test/file_test.py
Closes #1329 
Will probably need some serious examination for unintended consequences
=> Issue #1329

src/ui/src/js/configs/routes.js, src/ui/src/js/controllers/add_command_publishing_blocklist.js, src/ui/src/js/controllers/admin_system.js, src/ui/src/js/controllers/command_index.js, src/ui/src/js/controllers/command_publishing_blocklist.js, src/ui/src/js/controllers/command_view.js, src/ui/src/js/controllers/garden/export_garden_config.js, src/ui/src/js/controllers/garden/import_garden_config.js, src/ui/src/js/controllers/job/create_system.js, src/ui/src/js/controllers/job/export_jobs.js, src/ui/src/js/controllers/job/import_jobs.js, src/ui/src/js/controllers/system_index.js
Closes #1343
Removes redundant system call and sets the system data when it makes the garden call.
=> #1343 - Remove redundant system call from frontend
