docker/docker-compose/docker-compose.yml
docker/docker-compose/grafana/dashboards/performance_dashboard.json
docker/docker-compose/grafana/dashboards/plugin_performance_dashboard.json
docker/docker-compose/grafana/provisioning/dashboards/beer-garden.yaml
docker/docker-compose/grafana/provisioning/datasources/beer-garden.yaml
docker/docker-compose/prometheus/prometheus.yml
resources/grafana_dashboards/beer-garden-performance_rev2.json
resources/grafana_dashboards/plugin-performance_rev1.json

This is for  beer-garden/beer-garden#69
You should probably look at the following before merging:
* https://github.com/beer-garden/brew-view/pull/66
* https://github.com/beer-garden/bartender/pull/29
Changes to the docker-compose to include grafana and prometheus
by default. This enables our metrics to be scraped and the
default installation of beer-garden to be monitorable.
I added the two dashboards I created. You might notice they are
in two spots. There is a reason for this. The dashboards located
at `resources/grafana_dashboards` are the dashboards that get
uploaded to grafana.com.  These can be imported and when they
get imported by people, they get a prompt asking them to point
the dashboards at a prometheus datastore. Unfortunatley, you
cannot do the same for the "provisioned" …

Adding Grafana Dashboards

---

src/app/beer_garden/api/http/__init__.py

This PR removes the static file handlers from the Tornado configuration.

Removing static file handlers from http url map

---

src/app/beer_garden/api/http/__init__.py
src/app/beer_garden/api/http/handlers/misc.py
src/app/beer_garden/config.py
src/app/beer_garden/local_plugins/loader.py
src/app/example_configs/config.yaml
src/app/test/config_test.py

This PR removes an issue I've been bitten by a couple of times. It normalizes the url_prefix config values when they are loaded, which removes the need to call `normalize_url_prefix` everywhere the value is used.

Url prefix

---

src/app/beer_garden/local_plugins/manager.py
src/app/test/local_plugins/manager_test.py
src/app/test/local_plugins/registry_test.py

This PR:
- Removes unused functionality in the `LocalPluginManager` relating to pausing and unpausing a plugin
- Converts tests for `LocalPluginManager` and `LocalPluginRegistry` to pytest

Local tests

---

docker/docker-compose/docker-compose.yml

This is part of the fix for #352. Rabbitmq uses the hostname when constructing its "node name" so the random hostname that docker assigns by default could may cause rabbit to get confused.

Setting the hostname of the rabbitmq container

---

src/app/beer_garden/db/mongo/models.py

This is the counterpart to beer-garden/brewtils#158. Two fields have moved from the `Request` model to the `RequestTemplate` and that change needs to be reflected in the mongo models as well.

Mongo models

---

src/app/beer_garden/db/mongo/parser.py

This is really a problem for the anonymous principal. The
anonymous principal is actually a Brewtils object while the
MongoParser can only serialize Mongo objects. In the anonymous
case we need to fallback to the brewtils schema parser.

Fixes #382

---

src/app/beer_garden/__init__.py
src/app/beer_garden/__main__.py
src/app/beer_garden/app.py

This fixes #388, and also slightly tweaks the shutdown procedure so we don't join in the signal handler.

Reworking startup order to prevent hanging on an early shutdown

---

src/app/beer_garden/db/mongo/api.py
src/app/beer_garden/db/mongo/models.py
src/app/test/db/mongo/models_test.py

This PR moves Request status change validation into the Beer-garden database layer.
This depends on (and is the other half of) beer-garden/brewtils#179 and is occurring as part of beer-garden/brewtils#92.

Moving Request status change validation into Beer-garden

---

src/app/beer_garden/db/mongo/models.py

This PR fixes #141 by adding a `reverse_delete_rule` for the Command model's system field.

Adding a reverse_delete_rule for the Command model's system field

---

src/app/beer_garden/app.py
src/app/beer_garden/events/processors.py

When a Garden forwards an event to their parent, the event will have the forwarding Garden's name applied to it. This is because Parents have no concepts of Grand Children and would not know where the event came from if a Grand Child sent the event. This field is only for routing, so this is should be fine for these scenarios because the payload is not changed.
Also, added in the feature to skip events in the forwarding.

Change Forward Event Garden

---

src/app/beer_garden/db/api.py
src/app/beer_garden/events/handlers.py

This checks the MongoDB model to determine any unique fields required for storage. Then queries the database to determine if the record already exists. If the record already exists, then it verifies that the records are the same based on the ID.
Child BG instances can only create new records in their parent and update records that they know of. If a child tries to overwrite something the parent or other child created (i.e. identical plugin deployments) then the parent will reject the event request.
** Also removed DB events, this caused a loop in the code.

Child Event Checks

---

src/app/beer_garden/__main__.py
src/app/beer_garden/api/entry_point.py
src/app/beer_garden/api/http/base_handler.py
src/app/beer_garden/api/thrift/__init__.py
src/app/requirements.in
src/app/requirements.txt
src/app/setup.cfg
src/app/setup.py

This PR keeps the thrift entry point code but removes all references to thrift outside of the thrift package. It also removes `thriftpy2` from the dependency list.
It also changes the `EntryPoint` class to dynamically import the entry point packages instead of assuming they were already imported (which is why `beer_garden.api.http` and `beer_garden.api.thrift` no longer need to be imported in `__main__`).

Thrift cleanup

---

src/app/beer_garden/api/http/__init__.py

This PR fixes an issue where both the main process and the HTTP entry point would attempt to start the metrics server. Since they both tried to use the same port the HTTP entry point would error.
Also, starting the same thing in both processes is not needed :smile:

Metrics server should only be started in main process

---

src/app/beer_garden/config.py
src/app/example_configs/config.yaml
src/app/test/config_test.py

This PR makes some tweaks to the config subsystem:
- Removes the `brew_view` events section that is OBE
- No longer freezes the config when loading it. Freezing is nice, but it breaks the case where the server secret hasn't been set as we're unable to update it.
- The spec default for enabling sending event notifications to a parent needs to be `False` - the default needs to be standalone mode.

Config updates

---

src/app/beer_garden/api/http/authorization.py
src/app/beer_garden/api/http/base_handler.py
src/app/beer_garden/api/http/handlers/v1/event.py

This PR fixes a tricky little issue that we've seen before. Adding a function to the `auth_providers` list in a handler `__init__` is a really bad idea since a new handler is constructed (and so another provider is added) for every request.
This means that, over time, each new request will be checked against a bunch of redundant functions for potential authorization.
We did this in the `BaseHandler` at one point and the slowdown eventually got so bad that the server would fall over :smile:
Doing this in a specific handler isn't *quite* as bad, but yeah. I've also made that a `frozenset` instead of a list so this hopefully doesn't happen again.

Fixing incorrect auth provider list setup for the event websocket

---

src/ui/src/styles/custom.css

This is a tiny PR that fixes an annoying issue. Previously you could scroll down an amount equal to the width of the top navigation bar even if there was no content warrants it. This fixes that - you can no longer scroll down if there's nothing to scroll for.

Removing extra css rule that made page too large

---

src/ui/src/js/controllers/request_index.js

When I added the namespace column to the request index page I forgot to add a corresponding filter for it. Oops!

Fixing request index page filters

---

src/ui/src/index.html
src/ui/src/styles/custom.css

~~This changed the side menu to only have system information. Everything else is at the top.~~
~~Issue:~~
~~The Namespaces would not collapse for me. I don't know if this is because it is a dynamic list.~~
~~Another Note:~~
~~I just randomly put them in an order, if we want to re-arrange them we can.~~
This now moves everything to the top bar. Giving the user the entire width of their display. The logo in the top left is now a drop down menu to allow them to quickly navigate to a system. It searches all fields of the plugin, including description. Hoverover of the systems give the system description as well.

Moved Menu Around

---

src/app/beer_garden/app.py
src/app/beer_garden/events/processors.py

This PR fixes an issue where the application wouldn't shut down cleanly if it could not connect to mongo.

FanoutProcessor no longer starts child processors before it starts

---

src/app/beer_garden/local_plugins/manager.py

This change will allow developers to self manage the Python environment. If they do not provide a Python Path then it will default to path the Beer Garden is using.
Fixes #492

Provide PYTHONPATH in beer.conf

---

src/ui/src/index.html
src/ui/src/js/run.js

Trying to clean up how we have our drop down menu in the top right.
Previous the menu was as followed:
```
About
---------
default
slate
--------
Systems
Queues
Users
Roles
Gardens
```
Now the menus are broken out into three sections: Main, Themes, and Admin. When you click on the option it will open the sub-menu. Not sure if only Themes should be like this, but I went ahead and did the Admin actions the same way to see how it looks.

Create sub menus

---

src/ui/src/js/controllers/command_view.js

This fixes an issue where the console would throw a bunch of errors whenever the command view page was loaded for a system with more than one instance.

Fixing command view bug when no default instance

---

src/app/beer_garden/api/entry_point.py
src/app/beer_garden/log.py
src/app/test/log_test.py

This PR fixes some issues with logging:
- If a plugin logging configuration file isn't specified the app will now just use brewtils' defaults instead of crashing the entry point.
- If something to crash the entry point *does* happen we now the logs back to the main process so we can see them in situations where we can't easily see the process stderr (e.g. systemd).

Logging fix

---

src/app/beer_garden/__init__.py
src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/garden.py
src/app/beer_garden/local_plugins/runner.py
src/app/beer_garden/router.py
src/app/test/router_test.py
src/ui/src/js/controllers/admin_garden_view.js
src/ui/src/js/services/garden_service.js
src/ui/src/partials/admin_garden_index.html
src/ui/src/partials/admin_garden_view.html

When viewing the Gardens on the UI we couldn't see the local garden information. These changes will inject the Local Garden object when someone requests all of the Gardens. When someone attempts to make changes to the Garden it will not persist because it does not have an ID. When you restart with a new Garden name it will change that Garden info. If you select a Garden Name of a downstream Garden, you will see both in the UI but with different comments next to them (Local vs Remote).

Return Local Garden Info

---

src/ui/src/partials/admin_system.html

On the admin page we needed a way to display the namespace. This just adds it to the hyperlink.
fixes #527

Added Namespace to System Admin Page

---

src/ui/src/js/controllers/admin_garden.js
src/ui/src/js/controllers/admin_garden_view.js

Admin pages for Gardens now listen for events for live updates.
Ways to test:
1. Deploy child garden to see if it appears
2. Shut down child garden to see if status changes
3. Delete the Garden through the API and see if it is removed. 
Fixes #517

Added EventService implementations to both Garden Pages for Admins

---

docker/docker-compose/docker-compose.yml

Moving over the AMQ naming convention to the new MQ naming convention.

Migrated from AMQ to MQ (Docker Compose)

---

docker/docker-compose/plugins/docker-compose.yml

This updates the docker image to use the `v3` tag.

Using v3 tag for plugins docker image

---

src/app/beer_garden/local_plugins/env_help.py
src/app/beer_garden/local_plugins/manager.py

Fixes #542 - Needed to ensure all entries in the env dict are strings before expanding `$VAR` items.

Reordering beer.conf processing steps

---

src/ui/src/partials/about.html

Removed the Bartender and Brew View sections from the About Page. In a future PR, we should consider adding live statuses for the different components we have. It would also be nice to have indication for which version of the MongoDB and RabbitMQ we are connected to and their status. But this PR was only focused on the initial cleanup.
Part of #552

Removed Bartender and Brew View from About page

---

src/ui/src/partials/job_create.html

The scheduler page did not have namespaces present. So I added the field to support that.
Fixes #545

Added Namespace to Scheduler

---

src/app/beer_garden/api/http/__init__.py
src/app/beer_garden/app.py
src/app/beer_garden/events/handlers.py
src/app/beer_garden/log.py
src/app/beer_garden/monitor.py
src/app/beer_garden/plugin.py
src/app/beer_garden/systems.py

Created a generic monitoring tool for files. Then set this to monitor the logging-config.yaml and spawn an event when it changes. This event is captured by the Log.py handler and reloads the file. It also spawns commands to local plugins to reload their logging if they are Running. That way the changes can be immediate.
Easiest way to test this is to add and remove the file logging option. If you change the file directory or name you will see that change happen semi-immediately. 
The cool thing is now the logging file doesn't have to exist at startup. They can create it later and then those configurations will be applied automatically. 
Depends on: https://github.com/beer-garden/brewtils/pull/230
Fixes https://github.com/beer-garden/beer-garden/issues/532

Added auto-loader for plugin logger, including plugin updates

---

src/ui/src/index.html

This removes the Command Page button from the Top Menu. The page will still exist for navigating, but there is no need to have  a page to search all commands if you can use the search bar.
Fixes #559

Dropped Menu button for Commands Page

---

src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/local_plugins/manager.py
src/app/beer_garden/systems.py
src/app/test/db/mongo/models_test.py
src/app/test/local_plugins/manager_test.py

Updated logic to change the default `system.max_instance` to -1. If set to -1 then there is no upper limit to the instances that can be deployed.
Fixes #569

Changing default max instance to -1

---

src/app/beer_garden/monitor.py

Fixes a failure in the plugin logging config file monitor

Fixing monitor attribute name

---

src/app/beer_garden/api/http/handlers/misc.py
src/app/beer_garden/config.py
src/app/example_configs/config.yaml
src/ui/src/js/controllers/command_view.js
src/ui/src/js/controllers/request_view.js

This mostly fixes #360. That ticket is kind of a mess, but we can open a new issue for the parts not covered by this PR.
This PR implements the application-wide switch to control this. It changes the old, fairly unclear `allow_unsanitized_templates` config name to the much more direct `execute_javascript`. This config item will control whether the frontend will execute javascript anywhere. It doesn't really make any sense to have multiple flags - if javascript execution is allowed *anywhere* then you're completely trusting plugins, any half measures we could provide would just be security theater.

Enabling executable output on request view page

---

src/app/beer_garden/api/http/processors.py

This should fix the issue with the broken pipe:
```
Exception in thread Thread-6:
Traceback (most recent call last):
File "/home/mppatri/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/home/mppatri/git/beergarden/beer-garden/src/app/beer_garden/events/processors.py", line 86, in run
self.process(self._conn.recv())
File "/home/mppatri/.pyenv/versions/3.7.4/lib/python3.7/multiprocessing/connection.py", line 251, in recv
return _ForkingPickler.loads(buf.getbuffer())
_pickle.UnpicklingError: invalid load key, '\x00'.
```

Syncing buffer writes by making them asyncio

---

src/app/beer_garden/router.py
src/app/beer_garden/systems.py

This PR changes routing updates to happen explicitly when system changes are executed locally rather than catching and handling the event that's generated when those changes happen.
It adds simple locking to help with concurrency issues in the HTTP entry point.

Routing sync

---

src/app/beer_garden/requests.py

Changed the Event handling for Beer Garden Shutdown event to close open connections for Requests if the Shutdown event is spawned from the local garden environment. This will ensure all processes close during shutdown, and handles the edge case of Jobs tasking commands that are offline.
Fixes #602

Updated event handling for Garden shutdown

---

src/app/beer_garden/api/http/__init__.py
src/app/beer_garden/api/http/base_handler.py
src/app/beer_garden/api/http/client.py

This depends on #620, and is part of #611 
This transforms the `ExecutorClient` into a `SerializeHelper`. It no longer executes the routing operation (and then the actual operation) inside of a `ThreadPoolExecutor`. The route operation is now just called directly and the client is used as a serialization helper.
Future work could be to either remove this class completely or pull it up to the entry point level (or the router) where it can be used by all entry points.

Not using ThreadPoolExecutor for everything in HTTP package

---

src/app/beer_garden/app.py
src/app/beer_garden/events/parent_procesors.py
src/app/beer_garden/events/processors.py

When a child garden disconnects from the parent the child will go into a back-off state until it is reconnected. At the disconnect the queue is purged and no new events are accepted into the processor. Then once reconnected it runs any reconnect actions provided (Publish Garden Start Event) and begin accepting new events.
Fixes #607

Child Gardens Back-Off

---

src/app/beer_garden/api/http/handlers/v1/system.py
src/app/beer_garden/router.py
src/app/beer_garden/systems.py
src/ui/src/index.js
src/ui/src/js/controllers/admin_system.js
src/ui/src/js/controllers/admin_system_force_delete.js
src/ui/src/js/services/system_service.js
src/ui/src/templates/system_force_delete.html

Added the functionality to force delete a System record from the database. This does not take into consideration RabbitMQ or shutting down the plugin. If the plugin is still operational it will throw errors, but this is the last resort to deleting systems if you get in a bad state. So we ask like 3 times if you are sure.
Fixes #526

Added Force Delete for Systems.

---

src/app/beer_garden/scheduler.py

The scheduled was not getting the latest status from the request after our recent refactoring. This will grab the request object if it is required.
Fixes #665

Grab the request object if the Job still exists for status

---

src/app/beer_garden/router.py

This fixes #673. It translate an empty string namespace filter param for the SYSTEM_READ_ALL operation to the local garden name.

Translating empty string to garden name for SYSTEM_READ_ALL

---

src/ui/src/js/controllers/command_index.js
src/ui/src/js/controllers/request_index.js
src/ui/src/js/controllers/system_index.js
src/ui/src/partials/command_index.html
src/ui/src/partials/system_index.html

This starts addressing #560. Only the request index page is done, but the solution should be easy to expand to the other tables.

Storing request index length in local storage

---

src/app/beer_garden/api/entry_point.py

Helps with #701, should at least result in the app starting even if one entry point fails during creation.

Better entry point isolation during creation

---

rpm/centos7/scripts/after_install.sh

Fixes a bug with rpm installation related to new config names.

Correcting new plugin logging config names in rpm script

---

src/ui/src/index.js
src/ui/src/js/run.js
src/ui/src/js/services/token_service.js

This changes the default frontend storage to `localStorage` and explicitly uses `sessionStorage` for all token-related things. Since we don't actually support the login capability on the frontend yet that isn't strictly necessary, but I think it's what we'll want to do when we re-add that functionality.

Dt selection

---

src/app/beer_garden/db/mongo/jobstore.py
src/app/beer_garden/scheduler.py

The APScheduler was not getting passed the Trigger Object when the event was being created, so this now creates the trigger object and passes it forward. Now Date Triggers will display the proper next fire date and fire when expected.

Fixed Scheduler for Dates

---

src/app/beer_garden/router.py

Downstream gardens were not syncing their local environment because the local garden is no longer included in the Gardens routing object.

Child Garden Sync Error

---

.travis.yml

This is a temporary band-aid for #742. It looks like Travis has a PR for a fix to their deployment utility that should allow us to revert this once it's in use.

Temporary workaround to fix travis version conflict

---

src/app/beer_garden/api/entry_point.py

This is another part of #770. This PR prevents a premature termination of entry point processes when running under systemd.

Using SIGUSR1 for stopping entry points

---

src/app/beer_garden/local_plugins/manager.py
src/app/beer_garden/systems.py

Had two options to check, one was check the LPM or check the Metadata. Opted to check the LPM just in case another Beer-Garden is managing the Runner and populated the Metadata field.
Fixes: #794

Fixes delete of Remote Systems

---

.github/workflows/tag-actions.yml

Adding a check to make sure that the PyPI repo makes Beer Garden available. This does burn a couple cycles of compute time, but things are moving too fast and we need to make sure all of the repos are there.

Updating Actions to wait for PyPi to be ready

---

src/app/beer_garden/router.py

If garden gets updated and has no configuration would get a attribute error for `event.payload.connection_type.casefold()` not having attribute `casefold()` for object type `None`. Added check to see if object is none

Fixed attribute error

---

src/app/beer_garden/router.py
src/app/beer_garden/systems.py

Beer Garden will now wait on the response from Child Gardens. When we migrate to ASyncio this will improve performance. 
If we capture a router error during the forward of a Forced System Delete, then we will process it locally. That way at a minimum the System Admin can delete the record out of their database. 
fixes: #749

Handle Force Deletes for Child Systems

---

src/app/beer_garden/local_plugins/manager.py

Adds a warning for a tricky `beer.conf` configuration problem. Fixes #796.

Adding warning if beer.conf results in no instances to start

---

.github/workflows/tag-actions.yml

If PyPI is already deployed, this allows the actions to run off that existing release. Allowing for debugging of downstream actions.

Allow tagging to existing PyPi releases for deployments

---

src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/db/mongo/util.py
src/app/beer_garden/files.py

This addresses some serious flaws with the request migrations:
- Now works for child requests
- Doesn't change the updated_at timestamp
There is still work that needs to be done to bring these changes in line with other changes. Specifically, the File model `request` and `job` fields are not updated yet.

Better database migration

---

rpm/centos7/resources/service/beer-garden.service

This helps with #816. It makes the beer-garden group (not just user) have write permissions on created files in /opt/beer-garden.

Service now runs with 0002 umask

---

src/app/Makefile
src/app/beer_garden/files.py
src/app/test/file_test.py

Refactored some of the file code to increase code reuse.  
There were lots of places that used the `_unroll_object` function with the same set of ignore filters, so a new abstraction was made to simplify those code snippets.
Improvements made to the recursive parameter search to be more pythonic.

Refactoring File Service

---

src/ui/src/partials/admin_system.html

Adds description under the versions label in the systems admin page.
Fixes #840

Add descriptions to system admin page issue  #840

---

docker/docker-compose/docker-compose.yml

Set default value for `BG_ENTRY_STOMP_ENABLED` in docker to be false, so STOMP connection is not enabled by default.

changed STOMP default to false

---

src/app/beer_garden/api/http/__init__.py

Fixes #875, add support for unicode garden names
@TheBurchLog you may want to do the same thing for the Users api?

Adding % to garden url regex so encoded unicode will match

---

src/app/beer_garden/router.py

Fixes #893, always returns the request model object after forward attempt.

Always returning request create model from forward

---

src/app/beer_garden/router.py

Now we will actually use the SSL properties provided through the UI when connecting to Children
fixes: #897

Use SSL configuration provided by UI Garden Admin Form

---

src/ui/src/js/services/garden_service.js

Removed the drop down for Local Connection Type on the Garden Edit page. This will prevent Admin's from accidentally bricking their Garden editor.
Fixes: #906

Remove Local Garden Connection Type

---

src/app/beer_garden/requests.py

The main processor and every Entry Point spins up a Request Listener for Events. This causes duplicate events to be sent across Beer Garden, as intended so any entry point can get an event that they are waiting on. This is also causing a race condition when a Child Garden creates a Request because now two processors are attempting to duplicate that in the Parent database. For now, we will just catch this exception until we have a better approach for handling events.
fixes: #902 
Just realized this was the same solution I came up with in PR #746

Catching exception caused from multiple Request Event Processors

---

src/app/beer_garden/api/stomp/server.py
src/app/beer_garden/api/stomp/stomp_manager.py
src/app/beer_garden/router.py
src/ui/src/index.js

Fixed error that cause Beer Garden not to start when garden is configured to use stomp but is the field in config are empty. Also added logger warning message for connection failures to include a list of gardens affected so if the problem is with the connection config you can find which gardens to check in the logs.
Fixes #907

Fixed Bad Config Preventing Startup

---

src/app/beer_garden/__init__.py
src/app/beer_garden/api/http/__init__.py

This is just a test for the API code that was failing the lint checker. It was failing because the values were not declared.... So I declared them as None and it works. Not sure why it doesn't also hit `server`, `tornado_app`, or any of the other ones.

Fixing HTTP Linting Error

---

.github/workflows/integration-actions.yml
test/integration/gardens/setup/garden_setup_test.py

Fixing the errors in the overnight actions for Garden to Garden testing. The new `client` decorator is not on the Echo Plugin, so we will use that one.

Reducing to testing only with Echo for Garden setup

---

src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/scheduler.py
src/app/test/db/mongo/models_test.py
src/app/test/scheduler_test.py

When creating a Job, the namespace field is not required to be populated.

Namespace not required for Jobs

---

src/app/beer_garden/api/stomp/manager.py

This wraps the event handling for the stomp entry point in a try so it doesn't cause problems if there's ever an exception.

Wrapping all stomp handler calls in a try

---

src/app/beer_garden/systems.py

Fixes #1002 by allowing empty strings to be set as system attributes.

System update now allows empty strings

---

test/integration/helper/plugin.py

This helps with #1014, even though it's already closed. It tweaks the integration tests so they can successfully test versions of brewtils where this was a problem.

Integration tests for old version of brewtils now pass

---

rpm/centos7/resources/nginx/bg.conf
src/ui/default.conf.template

Fixes #1027, adjusts nginx configs to allow larger request bodies.

Adding client_max_body_size directives to nginx configs

---

src/app/beer_garden/events/parent_procesors.py

Fixes #1035. Improves error handling in the event of a broken HTTP connection to a parent garden.

Reconnect loop also needs to be inside a try

---

src/app/beer_garden/requests.py

Related to #1040.
The linked PR modified handling of an invalid request to publish an event with the Request's status set to INVALID. That allows invalid downstream requests to be detected properly on the upstream. However, that breaks the integration tests that are expecting non-200 response codes.
This PR tweaks the error handling to do both.

Publishing an event AND raising the exception for bad reqeusts

---

src/app/beer_garden/api/http/__init__.py
src/app/beer_garden/api/stomp/__init__.py
src/app/beer_garden/router.py

Misc cleanup.
`beer_garden.router.forward_processor` was originally the queue used to ship requests to child gardens. Things would be put on the queue and immediately return. I think the purpose of this was to minimize the time spent blocking the http entry point's ioloop?
It's no longer used, I think mostly because error handling is such a pain. We don't have any good way to inform the frontend if there was an issue forwarding the request, which is bad. So we currently just push the request to the child garden immediately in the same thread context. The changes in this PR should have been made at the same time as that change, so this just fixes that oversight.
Last thing - the file parameter forwarding still has references to the `forward_processor`. I'm pretty sure this wasn't working …

Removing forward processor

---

src/app/beer_garden/api/http/handlers/vbeta/chunk.py
src/app/beer_garden/api/http/handlers/vbeta/file.py

This modifies the Resolvable model to have a toplevel `id` field. Depends on beer-garden/brewtils#331

Supporting Resolvable toplevel id field

---

.github/workflows/assign_project.yml

Closes #1064 
This will assign newly opened issues to the Backlog project and place them in the "New Issues" column.

#1064 - Add github action to assign new issues to the Backlog project

---

src/app/beer_garden/config.py
src/app/beer_garden/systems.py
src/app/example_configs/config.yaml
src/app/test/systems_test.py

Fixes #958. I'm unsure if `allow_update_systems` might be too vague of a config option. The description in `config.py` suffices, though.
Tested with brewtils' `update_system`.

Issue/958 - Added config option for changing commands of non-dev systems

---

src/app/beer_garden/requests.py

Fixes #1057 - child requests on a downstream garden should now be properly updated in the UI.
- Set up parent and child gardens named 'parent' and 'child'
- Run the `echo` example plugin on the parent garden
- Run the `sleeper` example plugin on the child garden
- Modify the `echo-sleeper` plugin so that the SystemClient targets the sleeper plugin on the child garden:
```python
self.sleeper_client = SystemClient(system_namespace="child", system_name="sleeper")
```
- Use the parent garden UI to create a `say_sleep` request
- On the request view page click the request to expand the child request view
Before this PR the status of the child request targeted at the parent garden would appear and update normally. However, the child request targeted at the child garden would either fail to …

Republishing a modified event when child request changes

---

src/app/beer_garden/router.py
src/app/test/router_test.py

This fixes #1076, multi-level garden routing.
Prior to this PR the routing process would not attempt to determine the target garden for an operation if one already existed on the model. Due to how we handle garden visibility, this meant that requests would never be able to be routed more than one garden away.
This PR tweaks that process to always attempt to determine the target garden.
- Set up a parent -> child -> grandchild garden structure
- From the parent, attempt to create a request for a system on the grandchild garden. It should work as normal

Overriding operation target garden if necessary

---

src/app/beer_garden/scheduler.py

Fixes #1081, zombie jobs.
Updating the job count in the database after an execution was recreating the job if it was removed. This change uses the `modify` api to only update the necessary field.
This PR doesn't modify or add any tests as the scheduler doesn't currently have any. I'd like to merge this anyway and attempt a refactor + test coverage effort for the scheduler module separately.
To see this bug in action create a schedule job for a request that takes a while to complete. I used the `sleep` command, 60 seconds. Remove the job when you see the log message that the plugin has just started to sleep. You should be able to view the scheduler page and see the job isn't there. Then wait for the "I'm awake" log message - at that point refresh the scheduler page and you should see the …

Updating job counts no longer revives a removed job

---

src/app/beer_garden/api/http/__init__.py
src/ui/src/js/controllers/admin_garden.js
src/ui/src/js/services/garden_service.js
src/ui/src/partials/admin_garden_index.html

Closes #940 
This PR changes the routing regex for tornado to be less restrictive, allowing all characters. A further PR will be created to always urlencode garden names before routing so that users won't be able to create invalid garden names.
One minor issue is that the `(.*)` group will capture the ending slash of a url, if present. For example: 
In `.../api/v1/gardens/garden-name/`, the captured group will be `garden-name/` instead of `garden-name`.
This hasn't affected my ability to access the garden in any way, but I can't figure out what that group is used for. If it's an issue, maybe `([^/]+)/?` will be a better regex here, to include all characters except for `/`.
To test: 
- Create a garden with special characters in the name, such as `-`, `&`, or `%`.

#940 - Change garden routing to allow any garden name

---

src/ui/src/js/controllers/command_view.js
src/ui/src/js/services/request_service.js

Fixes #1087 - command-based choices will time out if the request takes longer than 30 seconds to complete.
1. Modify the `dynamic` plugin `get_choices` function to sleep for 31 seconds
2. Navigate to the command page for `say_specific_from_command` in a browser
3. Wait 30 seconds. An indication should appear with a tooltip indicating a timeout expired.

Waiting for a request to complete will now time out

---

src/ui/src/styles/custom.css

Part of #393.
By default AngularJS will wait for an element's animation to complete before hiding it. This can cause the choices loading indicator to hang around for a couple extra seconds. This css rule "fixes" that.

Adding css rule to help with hiding animated elements

---

src/ui/src/js/controllers/command_view.js

Fixes #1096. Command-based choices won't populate on initial page load until an instance is selected (instead of just trying to use the "default" instance).
1. Use the dynamic plugin
2. Create instances `d1` and `default`
3. Stop the `default` instance
Now go to the `say_specific_from_command` page. Previously, the request will spin for the 30 seconds and then time out. Now there should be an info icon telling the user to select an instance.
Selecting the `d1` instance should cause the choices population to work normally.
Selecting the `default` instance will still cause the request to spin for 30 seconds and then time out. However, this is now the correct behavior - the user has intentionally tried to populate choices using an instance that isn't running.

Choices no longer use "default" instance by default

---

src/app/beer_garden/api/http/handlers/v1/garden.py
src/ui/src/js/controllers/admin_garden.js
src/ui/src/partials/admin_garden_index.html

Closes #1100
This PR also removes all URL decoding from the UI - what the user sees as a garden name should be what's read directly from Beergarden's DB.
- Create gardens in the Beergarden UI with special characters (`@ # $ % ^ & *`)
- Ensure that no garden names double-encode
- Ensure that the URL for the 'edit config' page of a garden is properly URLencoded
Note that the issue linked to this PR says:
>Somewhat related, I also notice that the URL that you get directed to after creating a garden ends up being double-encoded. Meaning that if I create a garden named "g@rden", I should be redirected to:
>`/admin/gardens/g%40rden/`
... although, this PR does not encode the `@` symbol. This doesn't seem to cause an issue with routing, however.

Fix double URL encoding on UI

---

src/app/beer_garden/garden.py

Closes #1110 
* Unfortunately writing unit tests to verify the API responses isn't viable at the moment.
* To manually test, try doing a GET and a DELETE against /api/v1/gardens/notarealgarden.  You should get a 404 in each case (as opposed to a 200 and a 500 respectively).

#1110 - Return 404 from Garden API in appropriate situations

---

src/app/beer_garden/db/mongo/api.py
src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/db/mongo/util.py
src/app/beer_garden/garden.py
src/app/test/db/mongo/models_test.py
src/app/test/db/mongo/util_test.py
src/app/test/garden_test.py

Closes #1092
Closes #727
This takes the garden name as defined in the config file and creates a Garden entry for it in the database.  It then updates the appropriate places to pull said entry from the db when appropriate.
Things still exist in a slight in-between land in this PR, meaning there are still some distinctions between local and remote gardens that have to be accounted for.  Specifically, local gardens don't get the list of embedded System documents that remote gardens have, and instead that data is assembled in real-time when requested.  This is not ideal, but it's the easiest way to maintain compatibility as we make the incremental model changes necessary for all of the auth stuff.  There are comments in the code that explain why certain things had to hang around.
I wrote a …

#1092 - Store local garden info in the database

---

src/app/beer_garden/garden.py
src/app/test/garden_test.py
src/ui/src/js/services/garden_service.js

Closes #1104 
The idea behind this change is to use Yapconf to specify default connection parameters for each newly created garden, then overwrite these defaults with the user-specified config.
Worth noting is the difference in specification between `_ENTRY_SPEC` in `config.py` and the form created for the UI in `garden_service.js`. As far as I understand, these should match each other, so I changed the UI end to reflect how `_ENTRY_SPEC` looks. 
- Create a new garden in the UI
- Ensure Garden edit page is populated with default values (defined in `config.py`)
- Create a new garden using the API, specifying at least one config option under the garden's `connection_params` (e.g. specify a non-default port).
- Ensure the new garden reflects your changes in the Garden edit page.

#1104 - Explicitly write default Garden configs upon Garden creation

---

src/app/beer_garden/api/http/__init__.py
src/app/beer_garden/api/stomp/manager.py
src/app/beer_garden/events/handlers.py
src/app/beer_garden/files.py
src/app/test/events/handlers_test.py

Closes #978 
Sending references to events before sending them to handlers might mangle the event between handler calls. This PR sends a copy instead to prevent that behavior.
Affected handlers are in the following files. Doing things in the UI that create events involving each of these modules would be sufficient testing.
```python
beer_garden.application.handle_event,
beer_garden.garden.handle_event,
beer_garden.plugin.handle_event,
beer_garden.requests.handle_event,
beer_garden.router.handle_event,
beer_garden.systems.handle_event,
beer_garden.scheduler.handle_event,
beer_garden.log.handle_event,
beer_garden.files.handle_event,
beer_garden.local_plugins.manager.handle_event
```

Deep copying events before sending to handlers

---

src/app/beer_garden/router.py

Integration tests are repaired. Though there remains a question of whether we're actually testing the functionality that we want to see in the garden stomp tests, but that discussion can wait for another day. In any case, local and remote integration tests pass after these edits.
Fundamental problem was in what seemed to be an innocent correction to the router code, adding in a default for a dictionary's `get` call. There's a comment in `src/app/beer_garden/router.py` that warns against doing the same again. But as the comment implies, we're doing checks before any routing occurs to handle different cases, but it seems unlikely that code ever runs. So we should look into that as well (but beware the attendant *whole other cans of worms*).

One line revert was not actually one line

---

src/app/beer_garden/db/mongo/models.py
src/app/test/db/mongo/models_test.py

Closes #1038 
Refactors `save()` in the `Request` Mongo model to transfer the request parameters or request output to GridFS. According to #1038, setting a cap of 5MB on both of these should keep the total size of the Request below 16MB (including other request data that needs to be saved), which is Mongo's limit..
- Run the unit tests
The unit tests may get more coverage with better Mongo model fixtures, but right now there are none.

#1038 - Better check for when requests need to be stored in GridFS

---

src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/garden.py
src/app/test/db/mongo/models_test.py

Closes #1101
To verify the fix for the corner case (running BG in a parent-child configuration,, taking the parent offline, changing Systems on the child, bringing the parent back up and then syncing), a straightforward way is to follow the steps in #1101 while tailing the log of the parent and then seeing that an error is no longer thrown. One could also track the entries in the database across the operations to make sure they are consistent with the actions taken and expected results. This was done with single parent and single child with each of http and stomp entrypoints and tested with multiple children and a grandchild with http. Corner case error appears to be resolved in all of these scenarios.
For the general case, two unit tests are provided to verify that any unknown Systems …

Issue/1101 - Delete stale systems when syncing child garden

---

.github/workflows/integration_tests_simple.yml

Closes #1139 
Runs the integration tests on Ubuntu 18.04, Python 3.8, brewtils *develop* and beer-garden *unstable* docker image. Claims to create a "Run Now" button on the action page on GitHub. Less useful than originally believed, but not a total waste since there have been times where I'd wished to run the integration tests manually against the main branch (this morning, for instance).

#1139 - Manual integrations tests on GitHub

---

src/app/beer_garden/api/http/__init__.py
src/app/beer_garden/api/http/authentication/__init__.py
src/app/beer_garden/api/http/authentication/login_handlers/__init__.py
src/app/beer_garden/api/http/authentication/login_handlers/base.py
src/app/beer_garden/api/http/authentication/login_handlers/basic.py
src/app/beer_garden/api/http/authentication/login_handlers/certificate.py
src/app/beer_garden/api/http/handlers/v1/__init__.py
src/app/beer_garden/api/http/handlers/v1/login.py
src/app/beer_garden/api/http/schemas/v1/login.py
src/app/beer_garden/config.py
src/app/example_configs/config.yaml
src/app/test/api/http/unit/handlers/v1/login_test.py

Closes #1134 
This PR adds a `/api/v1/login` endpoint that will be used for *initial* user authentication. That is, the user hits this endpoint, supplying their username and password (with a stub in there for future certificate based authentication) and gets back a JWT access token that is intended to be used to authenticate requests to all of the other (not /login) endpoints throughout the system when auth is enabled.
I'm going to list some URLs that reference `localhost:8080`. Substitute in appropriate values for however you are running your beer-garden instance.
* Create a user to test against:
```bash
curl -X POST --data '{"username": "obiwan", "password": "jedimaster"}' http://localhost:8080/api/v1/users
```
* Now if you send that same username and password to the login endpoint, you …

#1134 - Add user login endpoint

---

CONTRIBUTING.md

Just fixing minor inaccuracies in the contribution guide.  Main changes are:
* Suggesting people fork by default
* Referencing `make test` rather than `nosetests`

Minor fixes to the contribution guide

---

src/app/beer_garden/scheduler.py

Somehow a `raise Exception` call in `execute_job` got left in when that code got merged.  This is just removing that so the function runs as expected.  The fact that the unit tests pass with this exception in there though is a bad sign...

Remove (presumed) debugging Exception in execute_job function

---

src/app/beer_garden/db/mongo/models.py
src/app/test/db/mongo/models_test.py

Requires Brewtils [#358](https://github.com/beer-garden/brewtils/pull/367)
Adds the `status_updated_at` field to the mongo model. Included is a unit test that ensures it is not changed on a `save()`.

1132 - Add status_updated_at field to request model

---

src/app/beer_garden/scheduler.py
src/ui/package-lock.json
src/ui/package.json
src/ui/src/index.js
src/ui/src/js/controllers/job_view.js
src/ui/src/js/run.js
src/ui/src/js/services/job_service.js
src/ui/src/partials/job_view.html
src/ui/src/templates/reset_interval_modal.html

Closes #1062 
1. Schedule a job from the *Scheduler* page. It doesn't matter at this time what the trigger type of the job is.
2. From the *Request Scheduler* page, click the link for the job (i.e., the job's name ) in the *Job Name* column of the table on that page.
3. The resulting page has a *Run Now* button. Click it. Note that an information message is immediately shown in BG's logging indicating the job's been run. Note that a request with the time the button was clicked shows in the *Request* page and that the table entry reflects the correct job.
4. It's assumed that at some point in the future the "run now" API endpoint will accept a value indicating whether the interval should be reset when scheduling an ad hoc run of a job that has an interval trigger type. The code for this PR …

#1062 - Run now button

---

src/app/beer_garden/api/http/handlers/v1/job.py
src/app/beer_garden/scheduler.py
src/app/test/api/http/unit/handlers/v1/job_test.py
src/app/test/scheduler_test.py

Closes #1178
This PR fixes the lack of validation in the job import API such that it no longer creates Job entries for definitions that fail to pass validation.
It does this largely by replacing the direct interactions with pymongo in the `create_jobs` function with a simple wrapper around the `create_job` function, which saves each entry through the mongoengine model.
* Use the import API to import the following, which includes both a valid job definition and an invalid one:
```json
[
{
"name": "well_formed_job",
"misfire_grace_time": 3,
"trigger": {
"timezone": "utc",
"run_date": 1700000000000
},
"coalesce": true,
"trigger_type": "date",
"timeout": 30,
"max_instances": 3,
"request_template": {
"metadata": {
"request": "stuff"
},
"command": "speak",
"parameters": {
"message": "hey!"
}, …
```

#1178 - Improve job import API validation

---

src/app/example_configs/config.yaml
src/ui/src/js/controllers/command_view.js
src/ui/src/js/services/request_service.js

Closes: #1165 
Dependent on PRs: [angular-schema-form-addons: #39](https://github.com/beer-garden/angular-schema-form-addons/pull/39) and [angular-schema-form-builder: #26](https://github.com/beer-garden/angular-schema-form-builder/pull/26)
Adds support for bytes type in the UI.
Steps for testing
1. Clone branches [angular-schema-form-addons](https://github.com/west270/angular-schema-form-addons/tree/bg-issue/1165), and [angular-schema-form-builder](https://github.com/west270/angular-schema-form-builder/tree/bg-issue/1165). then run `npm build` on each branch.
2. In the `package.json` for the UI change the lines:
```
"@beer-garden/addons": "^3.2.0",
"@beer-garden/builder": "3.0.2",
``` 
to 
```
"@beer-garden/addons": "file:** path to angular-schema-form-addons **",
"@beer-garden/builder": …
```

issue #1165 adds support for bytes type in UI

---

src/app/beer_garden/api/http/handlers/v1/job.py
src/app/beer_garden/scheduler.py
src/app/test/api/http/unit/handlers/v1/job_test.py

Closes #1173
Does not require Brewtils [#369](https://github.com/beer-garden/brewtils/pull/375), but this PR is useful for testing.
- Create a job with an `interval` trigger of 30 seconds.
- Wait 15 seconds, then execute the job using the `execute_job` function from the Brewtils [#369](https://github.com/beer-garden/brewtils/pull/375) PR.
- Ensure the job is executed at the expected times - one time when the job is manually executed, then again 30 seconds later (45 seconds after the job was initially created). You can see execution times in Beergarden's logs in the console.
- Create a job without an `interval` trigger, ensure execution returns a `400` when `reset_interval` is True.

#1173 - Add 'reset_interval' option to ad-hoc executions of jobs

---

src/ui/src/partials/request_view.html

Closes #1142 
Adds a "Status Updated" column to a request's info table in the UI.
View any request in the Request View page to find the "Status Updated" column.

#1142 - Expose status_updated_at timestamp field on Request View page

---

src/app/beer_garden/requests.py

Closes #1209 
This PR adds a `None` check to `remove_bytes_parameter_base64` in `requests.py`.  It ought to never be called with `parameters=None` and I could not reproduce the situation where that happens, but logs received from a user indicate that this can in fact happen and so it should be handled.

#1209 - Handle parameters set to None in remove_bytes_parameter_base64

---

src/ui/src/js/configs/http_interceptor.js
src/ui/src/js/run.js
src/ui/src/js/services/token_service.js

Closes #1187
This PR attempts to fix the UI's refresh token handling.  Specifically it fixes a couple of behaviors:
* It's now possible to open new tabs or close and re-open a tab without having your session expire.
* Supplying an invalid token to the `/refresh` endpoint is handled more gracefully (shouldn't result in an unhandled rejection error in the console).
* Enable auth and login via the UI.
* Close the tab and then navigate back to beer-garden.  You should still be logged in.
* Ctrl click on something to open it in a new tab.  It should open and not prompt you to login again.  Try navigating around on the original tab, refreshing the page, etc.  You should still not be prompted to login.
* Click "Log Out" on one and then navigating around or refresh in another.  You should be …

#1187 - Improve UI handling of refresh tokens

---

src/app/beer_garden/api/authorization.py
src/app/beer_garden/api/http/handlers/authorization_handler.py
src/app/beer_garden/api/http/handlers/v1/forward.py
src/app/example_configs/roles.yaml
src/app/test/api/http/unit/conftest.py
src/app/test/api/http/unit/handlers/v1/forward_test.py

Closes #1207
This PR adds an authorization check to the `/api/v1/forward` endpoint.
* Your `superuser` role has the "event:forward" permission. Use the `example_configs/roles.yaml` or update your own config file if you are using some custom role config.
```shell
curl -si -X POST -H "Content-Type: application/json" --data '{"operation_type": "GARDEN_READ", "args": ["somegarden"]}' "http://localhost:8080/api/v1/forward" | head -1
```
* Create users with and without access:
```python
from mongoengine import connect
from beer_garden.db.mongo.models import Role, RoleAssignment, User
connect(db="bg-parent1", host="mongodb://mongodb")
read_only = Role.objects.get(name="read_only")
role_assignment = RoleAssignment(role=read_only, domain={"scope": "Global"})
user = User(username="ro_user", …
```

#1207 - Add global permission check to forward endpoint

---

.github/workflows/pull_request.yml
src/app/beer_garden/api/http/handlers/v1/request.py
src/app/test/api/http/unit/handlers/v1/request_test.py

Closes #1218 
This Pull request requires brewtils: 3.8.0
This PR fixes the request endpoint so that `children` gets properly populated.
The unit test should pretty well cover this one, but for a functional test, just task the `nested-calls` command and then refresh the request page after it initially loads.  With this fix you should still see the child request on that page after the reload.  Before the fix they would disappear.
**NOTE**: Before the reload you can end up seeing a duplicate child event listed.  This is not a new bug and won't be addressed here.  It's an artifact of the requests finishing sufficiently fast that the initial API response contains the children, and then UI receives a published event on the websocket connection regarding the child request and just creates a …

#1218 - Populate children in the request endpoint response

---

src/app/beer_garden/api/http/handlers/v1/request.py
src/app/beer_garden/db/mongo/models.py
src/app/test/api/http/unit/handlers/v1/request_test.py

Closes #1221
This PR reverts the `RequestAPI.get` method back to using the `Operation` flow for retrieving the request.  This results in an extra database lookup explicitly for the authorization check, but ensures that all of the data that is not native to the Request model gets properly added to the request for the response.  In most other cases the `Operation` flow was left intact when adding the authorization checks and it should have been kept here as well, so this is effectively correcting that mistake.
Additionally, this PR reverts a likely unintentional change where gridfs output was being stored in its serialized form rather than raw.  A separate comment on this PR goes into more detail on that.
The unit test covers this one pretty well.  If you want to functionally test this you …

Fix gridfs output handling

---

src/app/beer_garden/api/http/handlers/v1/garden.py
src/app/test/api/http/unit/handlers/v1/garden_test.py

Closes #1230 
This PR restores the DELETE method on the gardens endpoint, which as inadvertently deleted in the 3.7.1 release.  It also adds the authorization checks and corresponding unit tests.
* Create a garden via the garden admin page on the UI.
* Go back to the garden admin page and click the "Delete <garden>" button.
* The garden should be deleted as expected.

#1230 - Restore garden endpoint DELETE method

---

src/app/Makefile
src/app/beer_garden/local_plugins/runner.py
src/app/test/local_plugins/manager_test.py

This PR adds isort to the `format` command in the Makefile.  It also cleans up a couple of B009 and B010 errors that were being reported by flake8 (only when run locally for some reason).

Add isort to make format, fix B009 and B010 flake8 errors

---

src/app/beer_garden/api/stomp/manager.py
src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/db/mongo/util.py
src/app/beer_garden/events/__init__.py
src/app/beer_garden/events/parent_procesors.py
src/app/test/db/mongo/models_test.py
src/app/test/db/mongo/util_test.py
src/app/test/events/init.py

closes #877
Added a new model for black listing commands to the database for preventing requests from corresponding commands to be sent to parent.
The requests blocked are base on the combination of namespace, system name, and command name.
Testing
1. start up a parent and child garden
2. in a python console import `CommandBlackList` and connect to child database
3. add command to black list 
```
CommandBlackList(
namespace="child_namespace", system="echo", command="say"
).save()
```
4. Run corresponding command from either the parent or child
Results
If command is ran from the parent the request should be stuck in the created status.
If command is ran from child the parent should not know about the request.

#877 - Added backend support for event blacklist by command

---

src/app/beer_garden/scheduler.py

Closes #1157 
This should fix a routing issue for scheduled jobs to child gardens. Previously, the scheduler tried to forward a `RequestTemplate` to the child garden when tasking for a job, but this changes that to a `Request` so as to fix problems with `RequestTemplate`s in forwarding.
- Set up a parent/child garden
- Schedule a job on the parent garden to make a request on the child garden
This PR has revealed two other issues:
- The Success/Error counter does not increment as expected. I found that the only time these values are incremented is right after the scheduler sends the request to the child garden. Sometimes, when the scheduler checks if the request's status is `SUCCESS` so that in can increment the success count, it's still `IN_PROGRESS`. This should be handled a different …

#1157 - Fix jobs failing routing when routing a spawned request to a child garden

---

src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/requests.py
src/app/test/db/mongo/models_test.py
src/app/test/requests_test.py
src/ui/src/partials/request_view.html

Fixes #1143
This PR fixes a number of issues related to the `status_updated_at` field on the Request model.
* The "Status Updated" column in the UI has been repositioned.  In the cases of a request with an error, "Status Updated" was positioned somewhat awkwardly in between "Status" and "Error Type" fields.  "Error Type" only shows up when there is an error, which is why the awkwardness of the positioning wasn't initially obvious.
* The "Status Updated" column is now properly displayed for child requests in the request view.
* `status_updated_at` should now be properly preserved on requests originating from child gardens.
That last bullet was sort of the whole point of the original ticket, which I apparently lost sight of when providing guidance and code review on the original PR.  I …

#1143 - Persist status_updated_at from child garden

---

src/app/beer_garden/api/stomp/manager.py
src/app/beer_garden/app.py
src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/events/__init__.py
src/app/beer_garden/events/parent_procesors.py
src/app/test/db/mongo/models_test.py
src/app/test/events/init.py
src/ui/src/js/controllers/request_index.js

closes #1213 
Added check to see if event errors can be sent to parent. It currently blocks error events that name starts with `REQUEST` and have no payload.
- Start a parent and child garden
- Add a raise somewhere in the critical path of request creation. The first line of the remove_bytes_parameter_base64 function in requests.py is a good choice.
- Restart the child garden and attempt to task something from it directly (i.e. don't go through the parent).
Result should be that the Requests page does not show `Updates Detected` and the error event should not be published in the parent logs.

#1213 - Improve handling of error events

---

src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/db/mongo/pruner.py
src/app/beer_garden/db/mongo/querysets.py
src/app/test/conftest.py
src/app/test/db/mongo/models_test.py
src/app/test/db/mongo/pruner_test.py
src/app/test/db/mongo/querysets_test.py

Closes #1215 
Closes #1216
This PR makes two improvements to the handling of FileField fields:
* The gridfs file referenced by FileFields in the `Request` and `RawFile` models will now be properly cleaned up when the model instance itself is deleted.
* The `Request` model's save() method no longer produces or orphans a bunch of duplicate gridfs entries.
To achieve this, the following was done:
* A `request` LazyReferenceField with a CASCADE delete rule was added to the RawFile model
* The existing `Request.save()` logic was moved into a `_pre_save()` and refined to remove gridfs duplication.
* A new `_post_save()` method on the Request model was added, which updates the `request` reference field on the appropriate RawFile to point to the newly saved Request.
* A …

#1216 - Clean up gridfs items when deleting Request and RawFile

---

src/app/beer_garden/scheduler.py

Closes #1225 
Change to increment job error count on exception (as opposed to just when the garden returns an error). This should fix issues where the job isn't being run for reasons unrelated to the request, yet the job error count is not incremented.
- Create a job using any command from the the `error` system, ensure that the error count increments on each run of the job.
- Create a job that raises an exception at the job level, as opposed to at the request level. In fact, it may even be sufficient to just insert a manual exception into the area the except block covers.

#1225 - Increment job error count in all cases

---

src/app/beer_garden/api/http/__init__.py
src/app/beer_garden/api/stomp/manager.py
src/app/beer_garden/requests.py

Closes #1214
This PR splits what was the `beer_garden.requests.handle_event` function into two separate functions that can be called in different contexts:
* `handle_event` is now called only by the main process and does all of the database updates.
* `handle_event_for_entrypoints` is called by the entrypoint (http and stomp) processes and only deals with the internal request map that is used to track wait events (allowing things like nested commands to work correctly).
The result of this change is the following:
* Only one set of database updates occurs during the request lifecycle.  For example, there would be one update for each of the REQUEST_CREATED, IN_PROGRESS, and SUCCESS status changes.  Prior to this change there would be one update for each of those **per process** (main, http, …

#1214 - Separate database and entrypoint handling for requests

---

src/app/beer_garden/api/http/authentication/__init__.py
src/app/beer_garden/api/http/base_handler.py
src/app/beer_garden/api/http/exceptions.py
src/app/beer_garden/api/http/handlers/authorization_handler.py
src/app/beer_garden/api/http/handlers/v1/event.py
src/app/beer_garden/api/http/processors.py
src/app/test/api/http/unit/handlers/v1/event_test.py
src/ui/src/js/run.js
src/ui/src/js/services/event_service.js
src/ui/src/js/services/token_service.js

Closes #1243 
This PR adds authorization checks to the events that get published on the websocket connections.  Prior to these changes, every connection received every message, regardless of the user's actual permissions.  With this PR, the flow goes like this:
* Client connects to the websocket
* An "AUTHORIZATION_REQUIRED" message is published to the client.
* The UI has a callback to handle this message and send an "UPDATE_TOKEN" message with the current access token.
* The server processes the "UPDATE_TOKEN" message and updates its record of the access token for this connection.  It will also publish an acknowledgement message named "TOKEN_UPDATED".
* Whenever messages would be published on the websocket connection, the user's permissions are checked (using the access token on record …

#1243 - Add authorization checks to websocket event publishing

---

src/ui/src/js/run.js
src/ui/src/js/services/event_service.js
src/ui/src/js/services/token_service.js

Closes #1247 
This PR adds preemptive access token refreshing to the UI.  Every 30 seconds the UI will check the current access token's expiration time and will do a token refresh if the expiration is 2 or fewer minutes away.
There's also a bug fix where the refresh token was being sent to the websocket when the access token was intending to be sent after a refresh.
* Start beer-garden with auth enabled
* Open the developer panel in your browser
* Login to the UI
* Look at the `/api/v1/socket/events` connection.
* Leave the tab open until 2 minutes prior to token expiration (13 minutes by default, but see tip below).
* You should see a token update message published from the UI to the server, as well as the "TOKEN_UPDATED" response.
**Tip**: You don't have to wait the full refresh …

#1247 - Add preemptive refresh of access tokens to the UI

---

src/app/beer_garden/api/http/__init__.py
src/app/beer_garden/api/http/handlers/v1/event.py
src/app/beer_garden/api/stomp/manager.py
src/app/beer_garden/events/handlers.py
src/app/beer_garden/requests.py
src/app/test/api/http/unit/handlers/v1/event_test.py

This PR fixes the job schedulers request handling so that it can properly keep track of which requests that it has kicked off have finished.  This was done by:
* Renaming `handle_event_for_entrypoints` to `handle_wait_events` to make it slightly more accurately named.
* Adding `handle_wait_events` to the list of processors that the Main process (which runs the scheduler) calls during its event processing.
It also fixes an issue where the auth check for events without a payload type would throw an error because the check function assumed there would always be a payload type.  A unit test has been added for this scenario.
Each of those fixes is isolated to their own commit, so look at the two commits if you're unsure which changes apply to which fix.

#1214 - Fix job scheduler request handling

---

src/app/beer_garden/events/handlers.py
src/ui/src/index.html
src/ui/src/index.js
src/ui/src/js/controllers/admin_garden_view.js
src/ui/src/js/controllers/garden/export_garden_config.js
src/ui/src/js/controllers/garden/import_garden_config.js
src/ui/src/js/services/garden_service.js
src/ui/src/partials/admin_garden_index.html
src/ui/src/partials/admin_garden_view.html
src/ui/src/templates/import_garden_config.html

Closes #1192 
Exercise the import and export functionality via the buttons. Note that:
1. There is minimal error checking and almost no validation. If an exported JSON file is mangled, the code makes a best-effort to avoid importing it. But if it's just augmented with garbage (that is otherwise legal JSON), or if it's entirely empty, it will import the garbage into the database. Caveat emptor. 
2. As a note on the STOMP tab says, if there are supposed to be headers but the fields are empty, the page must be refreshed. They should show up then. This is related to a shortcoming with angular-schema-forms and nested structures.

#1192 - Garden connection UI import/export

---

src/app/beer_garden/api/http/__init__.py
src/app/beer_garden/api/http/handlers/v1/user.py
src/app/beer_garden/api/http/schemas/v1/user.py
src/app/beer_garden/db/mongo/models.py
src/app/test/api/http/unit/conftest.py
src/app/test/api/http/unit/handlers/v1/users_test.py
src/ui/src/index.html
src/ui/src/index.js
src/ui/src/js/controllers/admin_user_index.js
src/ui/src/js/controllers/admin_user_view.js
src/ui/src/js/controllers/change_password.js
src/ui/src/js/run.js
src/ui/src/js/services/user_service.js
src/ui/src/templates/change_password.html
src/ui/src/templates/new_user.html

Closes #1262 
This PR adds password management to the UI.  There are two different places that this appears:
1) For all users, there is a new "Change Password" option in the top right ☰ dropdown menu.  This brings up a modal window where the user can change their own password.
2) On the admin only user management page where users' roles are managed, it is now also possible to change the user's password.
A new `/api/v1/password/change` API endpoint was also added to facilitate `#1`.
* Try to change a password using the two methods described above.

#1262 - Add password management

---

src/ui/src/js/controllers/request_index.js
src/ui/src/partials/request_view.html

Closes #1263 
This PR adds the "requester" column to the request index and view pages if auth is enabled.  The requester is also visible on child requests that spawn (such as on the `nested-calls` example plugin).
The original issue (as written) was for recording the username on the request, but it turned out that was already happening.  So surfacing that info in the UI was all that was needed.
Test Instructions:
* With auth disabled, go to the requests page.  It should not show a requester column.
* With auth enabled, task something and go to the requests page.  You should see a requester column with the username of the user that spawned the request listed.

#1263 - Show username on requests in the UI if auth is enabled

---

src/app/beer_garden/authorization.py
src/app/test/auth_test.py

Closes #1264 
This PR allows users to view requests where they are the requester, even if they do not have a role assignment explicitly granting access to the request.
This is done by defining a list of `OBJECT_OWNER_PERMISSIONS` that are conferred to users for any object where they are the owner.  This permission list is currently just `request:read`, and only requests are considered to have an owner, but this implementation allows for the potential expansion of both the eligible object types and the conferred permissions.
* Remove the "request:read" permission from the roles it is assigned to.
* Create requests as multiple users.
* Verify that each user can see their own requests, and only their own requests, since none of them will actually have "request:read" granted through any of …

#1264 - Allow implicit access to a user's own requests

---

src/app/beer_garden/api/http/handlers/v1/garden.py
src/app/beer_garden/api/http/schemas/v1/user.py
src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/events/handlers.py
src/app/beer_garden/garden.py
src/app/beer_garden/router.py
src/app/beer_garden/user.py
src/app/test/api/http/unit/handlers/v1/garden_test.py
src/app/test/conftest.py
src/app/test/garden_test.py
src/app/test/user_test.py

This is the backend portion of #1265.  A separate PR will be opened for the UI changes.
This PR adds backend support for syncing users from a local garden down to all remote gardens. As implemented it is an all or nothing proposition.  Doing a user sync will sync **all** users on the local garden with **all** remote gardens. Support for limiting the scope of the sync would not be difficult, but feels unnecessary at this time given the intended use case.
The workflow does something like this:
**NOTE:** other than the first bullet, all referenced functions are in `beer_garden/user.py`
* The `/api/v1/gardens` endpoint now supports a "sync_users" PATCH operation, which is used to initiate the user sync. This felt like the appropriate home both because of the all or nothing nature described …

#1265 - Add user syncing across gardens (backend-only)

---

AUTH.md
src/app/beer_garden/api/http/handlers/misc.py
src/app/beer_garden/app.py
src/app/beer_garden/config.py
src/app/beer_garden/db/mongo/api.py
src/app/beer_garden/db/mongo/util.py
src/app/example_configs/config.yaml
src/app/test/db/mongo/util_test.py

Closes #1274 
This PR adds steps to the garden initialization process that will create a default admin user, and create a default superuser role with all permissions that can be assigned to the admin user.
Some notes:
* The admin username and password can be customized via the app config.
* The admin user will not be created if any other users already exist
* The superuser role be created if it does not exist and there are no existing users.  Users existing indicates some setup has been done already and we preserve that setup.  An existing superuser role will never be modified.
* The code I touched had some references to the "guest_login_enabled" configuration option.  That option didn't do anything in the current iteration of beergarden, so I just opted to remove all references to it …

#1274 - Create admin user and superuser role on new garden startup

---

src/app/beer_garden/api/http/handlers/v1/event.py
src/app/beer_garden/api/http/handlers/v1/user.py
src/app/beer_garden/api/http/processors.py
src/app/beer_garden/api/http/schemas/v1/user.py
src/app/beer_garden/router.py
src/app/beer_garden/user.py
src/app/test/api/http/unit/handlers/v1/event_test.py
src/app/test/api/http/unit/handlers/v1/garden_test.py
src/app/test/user_test.py
src/ui/src/index.js
src/ui/src/js/controllers/admin_garden_view.js
src/ui/src/js/controllers/admin_user_index.js
src/ui/src/js/controllers/admin_user_view.js
src/ui/src/js/controllers/user/new_user.js
src/ui/src/js/controllers/user/sync_users.js
src/ui/src/js/services/garden_service.js
src/ui/src/partials/admin_user_index.html
src/ui/src/partials/admin_user_view.html
src/ui/src/templates/sync_users.html

Closes #1265 
This PR adds the UI components (and the API changes to drive the UI) for the user syncing.  With this PR the following changes are present in the UI:
* On the User admin index page there is a "Sync Users" button next to the "Create Users" button.  Clicking this brings up a modal that explains what the syncing is all about and lets you click "Sync" to start the process.
* The "Sync Status" for each garden is initially listed as "PENDING" if the garden is in a "RUNNING" state.  If the garden is not running, the sync status is just listed as "NOT RUNNING", indicating that we can't actually sync to that garden right now.
* Once "Sync" is clicked, a spinner will be shown in place of "PENDING" to denote that the sync is in progress.  Once the sync is done, it will change to …

#1265 - UI updates for user syncing

---

src/app/beer_garden/api/http/exceptions.py
src/app/beer_garden/api/http/handlers/misc.py
src/app/beer_garden/api/http/handlers/v1/token.py
src/app/test/api/http/unit/handlers/v1/token_test.py
src/ui/src/js/configs/http_interceptor.js
src/ui/src/js/controllers/login.js
src/ui/src/templates/login.html

Closes #1280 
This PR does the following:
* Provides feedback on the login form when authentication fails by displaying a message that reads "Invalid username or password".
* Attempts to auto-login a user if trusted header authentication is enabled.  This makes for a smoother experience where a user is not required to click the login button if they have already authenticated via their a proxy server that is passing along trusted headers.
Work on these changes highlighted the fact that the HTTP response code for failed logins had been incorrect (it was 401).  This PR changes that to 400 so that it failed login responses do not get caught up in the http interceptor code intended for handling actual data returning endpoints.
* In the login dialog, enter an incorrect username or password. …

#1280 - Improve login process

---

src/app/beer_garden/authorization.py

Closes #1284 
This PR makes the `user_permitted_objects` helper function work with the CommandPublishingBlockList model.  It does this by making "namespace" the default garden name field for the `_get_garden_name_field` function so that models that use that field don't explicitly need to be present in the model field map.

#1284 - Make namespace the fallback field for _get_garden_name_field

---

src/ui/src/js/controllers/request_index.js

Closes #1286 
This PR fixes an issue where the filter headers on the Request table were off by one when auth is disabled.  To fix this, the `$scope.dtOptions.lightColumnFilterOptions` is now constructed after `$scope.dtColumns` is finished being built.  This ensures that only columns that are actually present get added to the column filters.
With auth enabled and disabled, navigate to the Request index page.  The filter columns should properly align and work in both cases.  On develop, the later columns are shifted by one because the filter for the "requester" field was present even if the column was not.

#1286 - Correctly display column filters on request table

---

src/app/beer_garden/authorization.py
src/app/test/auth_test.py

Closes #1290 
This PR adds type enforcement to `user_has_permission_for_object` to avoid scenarios where an unsupported type could be passed in, resulting in undefined behavior.

#1290 - Add type enforcement to user_has_permission_for_object

---

docker/docker-compose/tls/docker-compose.yml
src/app/beer_garden/queue/rabbit.py

Closes #1288 
This PR makes changes to allow local plugins to properly connect to rabbitmq when it is setup to require client certificates.  Specifically, it now includes the full set of `mq_config.connections.message.ssl` settings instead of just `mq_config.connections.message.ssl.enabled` so that local plugins receive the location of the certificate file to use when connecting.
This should be tested in together with [brewtils/pull/390](https://github.com/beer-garden/brewtils/pull/390).
To test, you must setup rabbitmq to accept TLS connections and require client certificates.  You must then ensure that your `mq.message.ssl` and `mq.admin.ssl` settings are configured, with the client cert specifically pointing to a cert / key bundle.  With all of that configured, start up beergarden and …

#1288 - Fix to allow local plugins to connect to rabbitmq over TLS

---

src/app/requirements.txt
src/app/setup.py

Closes #1292 
This PR pins the version of yapconf and explicitly lists watchdog and pathtools, both of which were being used without being listed as direct dependencies.
A follow-up issue will be opened to look at updating yapconf and then updating or removing the dependency on watchdog and pathtools.

#1292 - List and pin missing requirements in setup.py

---

src/app/Makefile
src/app/docker/Dockerfile.debian
src/app/docker/Dockerfile.unstable-debian
src/app/docker/README.md
src/app/docker/docker-entrypoint.sh

This PR brings the debian docker image more in line with the configuration of alpine image, specifically in terms of the directories where things are stored and the user that the process runs under.

Make debian docker image more like alpine image

---

README.md
src/app/README.rst

Closes #1304 
This PR removes the gitter badge from the two READMEs in which it was present.

#1304 - Remove gitter references

---

src/ui/src/js/controllers/admin_garden.js
src/ui/src/js/controllers/admin_garden_view.js
src/ui/src/partials/admin_garden_index.html
src/ui/src/partials/admin_garden_view.html
src/ui/src/styles/custom.css

Closes #1299 
Added visual feedback in the form of alerts to garden sync and garden connection update on individual garden page. Informational alerts will disappear after 30 s, whereas error alerts must be manually dismissed. The garden management page also has alerts displayed for both success and error associated with the 'sync all' action.

#1299 - Add visual feedback to garden sync actions

---

src/app/beer_garden/api/authorization.py
src/app/beer_garden/api/http/handlers/v1/instance.py
src/app/beer_garden/api/http/handlers/v1/system.py
src/app/beer_garden/api/http/schemas/v1/system.py
src/app/test/api/http/unit/handlers/v1/instance_test.py
src/app/test/api/http/unit/handlers/v1/system_test.py

Closes #1301 
This PR does the following:
* Removes the `queue_type` and `queue_info` properties from Instances in responses from the /systems endpoints
* Changes the permissions needed to access the /instances endpoints from `SYSTEM_*` to `INSTANCE_*`.
This is done to make it so that the /systems endpoints no longer needlessly provide sensitive message queue connection information.  Meanwhile, access to the /instances endpoints which do include the sensitive connection information (specifically needed by a plugin registering itself with the garden), can be separately provisioned.
**NOTE**: As explained in the docstring for `_remove_queue_info`, the solution applied here is fairly unfortunate, but is by far the least intrusive solution.  Anything more involved is pretty hard to justify in …

#1301 - Remove queue connection info from system responses

---

src/app/beer_garden/api/http/handlers/misc.py
src/ui/src/partials/about.html

Closes #1118 
I don't think deleting the mentions of the old components in `beer_garden/src/app/beer_garden/api/http/handlers/misc.py` breaks anything, but let me know if it does.
In the actual About.html, I have removed the components section and simply made the Version Information section into one line of text. If we need something more there, just let me know.

Issue #1118

---

src/app/beer_garden/app.py
src/app/beer_garden/db/mongo/models.py
src/app/beer_garden/db/mongo/parser.py
src/app/beer_garden/db/mongo/util.py
src/app/beer_garden/scheduler.py
src/app/requirements-dev.txt
src/app/requirements.txt
src/app/setup.py
src/ui/src/js/controllers/job/create_trigger.js
src/ui/src/js/services/job_service.js

Closes https://github.com/beer-garden/beer-garden/issues/1295
This PR does the following:
- Removes the File Trigger from the UI
- Removes the file/async scheduled task processing from the server.
- Removes the direct beer-garden dependency on pathtools
*Note*: The watchdog lib is still used to load the logging configuration files and to watch for changes, so there is still the watchdog code in the server.
Test Instructions:
- Check the UI, make sure that the File Trigger isn't a trigger type and doesn't have settings to set
- Create a scheduled job, make sure that the request is executed as expected.
- Touch the `plugin.logging.config_file`, make sure the server still reloads the file.

#1295 - Remove file triggers and explicit dependency on pathtools

---

src/ui/src/partials/request_view.html

Closes #242 
Throwing style="white-space: pre-line;" in the html element with the comment fixes this in the individual request view. Test by running one of the plugins with a multiline comment then opening up the single request view. Didn't add this to the multi request table based on the comments in the issue

#242 - Add newlines to individual request view

---

src/app/beer_garden/config.py
src/app/beer_garden/db/mongo/util.py
src/app/example_configs/config.yaml
src/app/test/db/mongo/util_test.py

Closes https://github.com/beer-garden/beer-garden/issues/1309
This PR adds steps to the garden initialization process that will create a plugin_admin user, and create a default plugin role with limited permissions necessary to start and run a plugin.
Some notes:
The plugin_admin username and password can be customized via the app config.
The plugin_admin user will not be created if any other users already exist
The plugin role will be created if it does not exist. 
- Start a fresh instance of beergarden. 
- You should see log messages indicating that the plugin_admin user and plugin role are created.
- Without any other setup, you should be able to login to the UI as plugin_admin / password (unless you changed the defaults in your config).
- You will have limited permissions, for example, …

#1309 - Create plugin user and role on new garden startup

---

src/ui/src/js/controllers/admin_garden.js

Closes #1333
Fixes the close functionality of alerts on the garden admin page.
For testing click the sync all button on the garden admin page then try to close the alert

Fixes Unclosable Alert on Garden Admin Page

---

src/ui/src/js/controllers/request_view.js
src/ui/src/partials/request_view.html

Closes #1338 
User can click error pop-up or icon to choose to display large outputs. Added warning in pop-up text to do so at your own risk. Consolidated size checks for better handling.

issue #1338 - large output override

---

src/app/beer_garden/app.py
src/app/beer_garden/config.py
src/app/beer_garden/db/mongo/pruner.py
src/app/example_configs/config.yaml
src/app/test/db/mongo/pruner_test.py

Closes #249 
This PR gives the MongoPruner the ability to mark any requests that have been sitting in CREATED or IN_PROGRESS for longer than a specified amount of time as cancelled. There is now a setting in the configs called in_progress that holds that value

Issue 249: Tests written and passing

---

src/app/setup.cfg
src/app/test/local_plugins/runner_test.py
test/integration/setup.cfg

This PR fixes two linting errors:
* One in runner_test.py that was a legitimate error
* The other is an error, W503, that had previously been ignored by default, but recent changes in pycodestyle / flake8 make it so that we have to explicitly list it in the exclusions list.

Fix linting errors

---

src/app/beer_garden/api/http/handlers/v1/system.py

Closes #1345 
I relocated the function `_remove_queue_info` in the `SystemApi` patch so it would not try to parse an empty string.
For testing go to the systems admin page and click reload on a running system. The system should shutdown then restart without the error mention in issue #1345.

System Reload Error

---

src/app/beer_garden/api/http/__init__.py
src/app/test/api/http/unit/conftest.py
src/app/test/api/http/unit/handlers/v1/queue_test.py

Closes #1347 
This PR updates the url routes to be less strict on the allowed queue names.  Previously, only word characters plus hyphen were allowed.  This was problematic since the queue names are derived from instance names, which do not have this restriction.
Most of the code in this PR is refactoring the way the routes are defined so that they could be leveraged in the unit tests, rather than the unit tests having their own set of routes defined (a longstanding TODO).  This was necessary to allow a meaningful unit test to be written.
* The unit test pretty well covers this, so you could just look at that if you care to.
* To functionally test:
* Create a plugin instance with a name like "this->breaks"
* Go to the System Admin page and clear the queue for that instance.  Before this …

#1347 - Fix 404 response on queue DELETE

---

src/app/beer_garden/queues.py
src/app/beer_garden/router.py

Closes #1354 
This PR semi-fixes the call behind the "Clear All Queues" button on the system admin page.  It adds the necessary route for QUEUE_DELETE_ALL to the router, but only executes the operation on the local garden.  It does not attempt to pass the operation on to all downstream gardens.  Doing so would add a great deal of complexity for little gain and could also be confusing at best, and outright dangerous at worst due to the unreliable nature of the asynchronous event processing.
On the System Admin page, click the "Clear All Queues" button in the top right.  The operation should succeed (though there's no feedback in the UI).  If you look at the garden logs, you should see a bunch of INFO messages for each of the queues, showing that each one got cleared.  They'll look …

#1354 - fix QUEUE_DELETE_ALL operation routing

---

src/app/beer_garden/api/http/handlers/v1/instance.py

Closes #1356 
This PR fixes to the log viewing for plugins on the local garden.  Some functionality was refactored into a function for testing purposes at some point, but said function didn't actually return a value.  This fixes that.

#1356 - Fix issue related to viewing local plugin logs

---

src/app/beer_garden/api/http/base_handler.py

Closes #1361 
Add missing headers to allow CORS requests against API from production build of React UI

#1361 - add missing headers for CORS

---

.github/workflows/pull_request.yml
.github/workflows/release.yml
rpm/bin/build.py
rpm/bin/rpm_build.sh
rpm/centos7/resources/nginx/bg.conf

Closes #1363 
This PR updates the build script and github action to include the latest react-ui release in the RPM that gets built for the beer-garden release.  The result is that with the provided nginx config, the react version of the ui gets served up under the path `/preview`.
Manually testing this one is non-trivial, so I don't particularly suggest it.  You can see a successful run of the github action in my fork [here](https://github.com/scott-taubman/beer-garden/actions/runs/3184814284/jobs/5193659617), with the actual react portion of the build beginning [here](https://github.com/scott-taubman/beer-garden/actions/runs/3184814284/jobs/5193659617#step:5:177).  The release with the actual rpm artifact is found [here](https://github.com/scott-taubman/beer-garden/releases/tag/3.15.0). …

#1363 - Add react-ui to RPM build process
